// ============================================================
//  QuickBasket — data.js  |  200+ products, 15 categories
// ============================================================

const PRODUCTS = [

  // ——— DAIRY & EGGS ———
  { id:'milk_fc_1l',     name:'Full Cream Milk',          unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:68  },
  { id:'milk_tn_500',    name:'Toned Milk',               unit:'500ml',    emoji:'🥛', cat:'dairy',      basePrice:35  },
  { id:'milk_sk_1l',     name:'Skimmed Milk',             unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:62  },
  { id:'milk_oat',       name:'Oat Milk',                 unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:199 },
  { id:'milk_almond',    name:'Almond Milk',              unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:220 },
  { id:'butter_amul',    name:'Amul Butter',              unit:'100g',     emoji:'🧈', cat:'dairy',      basePrice:58  },
  { id:'butter_br',      name:'Britannia Butter',         unit:'100g',     emoji:'🧈', cat:'dairy',      basePrice:55  },
  { id:'curd_400',       name:'Fresh Curd',               unit:'400g',     emoji:'🫙', cat:'dairy',      basePrice:48  },
  { id:'curd_1kg',       name:'Fresh Curd',               unit:'1kg',      emoji:'🫙', cat:'dairy',      basePrice:95  },
  { id:'curd_greek',     name:'Greek Yogurt',             unit:'400g',     emoji:'🫙', cat:'dairy',      basePrice:115 },
  { id:'cheese_sl',      name:'Processed Cheese Slices',  unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:95  },
  { id:'cheese_spread',  name:'Cheese Spread',            unit:'180g',     emoji:'🧀', cat:'dairy',      basePrice:85  },
  { id:'paneer_200',     name:'Fresh Paneer',             unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:85  },
  { id:'paneer_500',     name:'Fresh Paneer',             unit:'500g',     emoji:'🧀', cat:'dairy',      basePrice:195 },
  { id:'ghee_amul',      name:'Amul Pure Ghee',           unit:'500ml',    emoji:'🧈', cat:'dairy',      basePrice:310 },
  { id:'ghee_pat',       name:'Patanjali Cow Ghee',       unit:'500ml',    emoji:'🧈', cat:'dairy',      basePrice:285 },
  { id:'cream_amul',     name:'Amul Fresh Cream',         unit:'200ml',    emoji:'🍶', cat:'dairy',      basePrice:55  },
  { id:'lassi_sweet',    name:'Sweet Lassi',              unit:'200ml',    emoji:'🥛', cat:'dairy',      basePrice:30  },
  { id:'buttermilk',     name:'Buttermilk (Chaas)',        unit:'500ml',    emoji:'🥛', cat:'dairy',      basePrice:28  },
  { id:'eggs_6',         name:'Eggs',                     unit:'6 pcs',    emoji:'🥚', cat:'dairy',      basePrice:48  },
  { id:'eggs_12',        name:'Eggs',                     unit:'12 pcs',   emoji:'🥚', cat:'dairy',      basePrice:89  },
  { id:'eggs_farm',      name:'Farm Fresh Eggs',          unit:'6 pcs',    emoji:'🥚', cat:'dairy',      basePrice:62  },

  // ——— FRUITS ———
  { id:'apple_sh',       name:'Apple Shimla',             unit:'1kg',      emoji:'🍎', cat:'fruits',     basePrice:180 },
  { id:'apple_fu',       name:'Apple Fuji',               unit:'1kg',      emoji:'🍎', cat:'fruits',     basePrice:220 },
  { id:'banana_dz',      name:'Banana',                   unit:'1 dozen',  emoji:'🍌', cat:'fruits',     basePrice:45  },
  { id:'mango_al',       name:'Alphonso Mango',           unit:'1kg',      emoji:'🥭', cat:'fruits',     basePrice:280 },
  { id:'mango_ke',       name:'Kesar Mango',              unit:'1kg',      emoji:'🥭', cat:'fruits',     basePrice:220 },
  { id:'orange_kg',      name:'Orange Kinnow',            unit:'1kg',      emoji:'🍊', cat:'fruits',     basePrice:90  },
  { id:'mosambi',        name:'Mosambi (Sweet Lime)',      unit:'1kg',      emoji:'🍋', cat:'fruits',     basePrice:75  },
  { id:'lemon',          name:'Lemon',                    unit:'6 pcs',    emoji:'🍋', cat:'fruits',     basePrice:25  },
  { id:'grapes_gr',      name:'Green Grapes',             unit:'500g',     emoji:'🍇', cat:'fruits',     basePrice:75  },
  { id:'grapes_bk',      name:'Black Grapes',             unit:'500g',     emoji:'🍇', cat:'fruits',     basePrice:80  },
  { id:'watermelon',     name:'Watermelon',               unit:'1 pc',     emoji:'🍉', cat:'fruits',     basePrice:65  },
  { id:'papaya',         name:'Papaya',                   unit:'1 pc',     emoji:'🍈', cat:'fruits',     basePrice:55  },
  { id:'pomegranate',    name:'Pomegranate',              unit:'1kg',      emoji:'🍎', cat:'fruits',     basePrice:160 },
  { id:'guava',          name:'Guava',                    unit:'500g',     emoji:'🍐', cat:'fruits',     basePrice:40  },
  { id:'pineapple',      name:'Pineapple',                unit:'1 pc',     emoji:'🍍', cat:'fruits',     basePrice:80  },
  { id:'strawberry',     name:'Strawberry',               unit:'200g',     emoji:'🍓', cat:'fruits',     basePrice:95  },
  { id:'kiwi',           name:'Kiwi',                     unit:'4 pcs',    emoji:'🥝', cat:'fruits',     basePrice:120 },
  { id:'pear',           name:'Pear',                     unit:'1kg',      emoji:'🍐', cat:'fruits',     basePrice:140 },
  { id:'coconut',        name:'Coconut',                  unit:'1 pc',     emoji:'🥥', cat:'fruits',     basePrice:45  },
  { id:'chikoo',         name:'Chikoo (Sapota)',           unit:'500g',     emoji:'🟤', cat:'fruits',     basePrice:50  },

  // ——— VEGETABLES ———
  { id:'tomato_1kg',     name:'Tomato',                   unit:'1kg',      emoji:'🍅', cat:'vegetables', basePrice:40  },
  { id:'onion_1kg',      name:'Onion',                    unit:'1kg',      emoji:'🧅', cat:'vegetables', basePrice:35  },
  { id:'potato_1kg',     name:'Potato',                   unit:'1kg',      emoji:'🥔', cat:'vegetables', basePrice:30  },
  { id:'spinach',        name:'Spinach (Palak)',           unit:'250g',     emoji:'🌿', cat:'vegetables', basePrice:28  },
  { id:'carrot',         name:'Carrot',                   unit:'500g',     emoji:'🥕', cat:'vegetables', basePrice:32  },
  { id:'broccoli',       name:'Broccoli',                 unit:'500g',     emoji:'🥦', cat:'vegetables', basePrice:68  },
  { id:'capsicum_gr',    name:'Capsicum Green',           unit:'500g',     emoji:'🫑', cat:'vegetables', basePrice:55  },
  { id:'capsicum_red',   name:'Capsicum Red',             unit:'500g',     emoji:'🌶️', cat:'vegetables', basePrice:85  },
  { id:'cauliflower',    name:'Cauliflower',              unit:'1 pc',     emoji:'🥦', cat:'vegetables', basePrice:45  },
  { id:'cabbage',        name:'Cabbage',                  unit:'1 pc',     emoji:'🥬', cat:'vegetables', basePrice:35  },
  { id:'cucumber',       name:'Cucumber',                 unit:'500g',     emoji:'🥒', cat:'vegetables', basePrice:28  },
  { id:'peas',           name:'Green Peas',               unit:'500g',     emoji:'🟢', cat:'vegetables', basePrice:55  },
  { id:'beans',          name:'French Beans',             unit:'250g',     emoji:'🫘', cat:'vegetables', basePrice:38  },
  { id:'ladyfinger',     name:'Ladyfinger (Bhindi)',       unit:'500g',     emoji:'🌿', cat:'vegetables', basePrice:45  },
  { id:'bittergourd',    name:'Bitter Gourd (Karela)',     unit:'500g',     emoji:'🥒', cat:'vegetables', basePrice:40  },
  { id:'bottlegourd',    name:'Bottle Gourd (Lauki)',      unit:'1 pc',     emoji:'🥒', cat:'vegetables', basePrice:30  },
  { id:'eggplant',       name:'Eggplant (Baingan)',        unit:'500g',     emoji:'🍆', cat:'vegetables', basePrice:35  },
  { id:'pumpkin',        name:'Pumpkin',                  unit:'500g',     emoji:'🎃', cat:'vegetables', basePrice:30  },
  { id:'garlic',         name:'Garlic',                   unit:'100g',     emoji:'🧄', cat:'vegetables', basePrice:35  },
  { id:'ginger',         name:'Ginger',                   unit:'100g',     emoji:'🫚', cat:'vegetables', basePrice:20  },
  { id:'greenchilli',    name:'Green Chilli',             unit:'100g',     emoji:'🌶️', cat:'vegetables', basePrice:15  },
  { id:'mushroom',       name:'Button Mushroom',          unit:'200g',     emoji:'🍄', cat:'vegetables', basePrice:65  },
  { id:'sweetcorn',      name:'Sweet Corn',               unit:'2 pcs',    emoji:'🌽', cat:'vegetables', basePrice:40  },
  { id:'beetroot',       name:'Beetroot',                 unit:'500g',     emoji:'🟣', cat:'vegetables', basePrice:42  },
  { id:'radish',         name:'Radish (Mooli)',            unit:'500g',     emoji:'⚪', cat:'vegetables', basePrice:25  },
  { id:'drumstick',      name:'Drumstick (Moringa)',       unit:'250g',     emoji:'🌿', cat:'vegetables', basePrice:35  },
  { id:'methi',          name:'Fenugreek Leaves (Methi)', unit:'250g',     emoji:'🌿', cat:'vegetables', basePrice:22  },
  { id:'coriander',      name:'Coriander Leaves',         unit:'50g',      emoji:'🌿', cat:'vegetables', basePrice:15  },
  { id:'curry_leaves',   name:'Curry Leaves',             unit:'50g',      emoji:'🌿', cat:'vegetables', basePrice:12  },
  { id:'pudina',         name:'Mint Leaves (Pudina)',      unit:'50g',      emoji:'🌿', cat:'vegetables', basePrice:15  },

  // ——— GRAINS, RICE & PULSES ———
  { id:'rice_bsm_1',     name:'Basmati Rice',             unit:'1kg',      emoji:'🍚', cat:'grains',     basePrice:120 },
  { id:'rice_bsm_5',     name:'Basmati Rice',             unit:'5kg',      emoji:'🍚', cat:'grains',     basePrice:550 },
  { id:'rice_sona',      name:'Sona Masoori Rice',        unit:'5kg',      emoji:'🍚', cat:'grains',     basePrice:350 },
  { id:'rice_brown',     name:'Brown Rice',               unit:'1kg',      emoji:'🍚', cat:'grains',     basePrice:145 },
  { id:'atta_5',         name:'Wheat Flour (Atta)',        unit:'5kg',      emoji:'🌾', cat:'grains',     basePrice:245 },
  { id:'atta_10',        name:'Wheat Flour (Atta)',        unit:'10kg',     emoji:'🌾', cat:'grains',     basePrice:470 },
  { id:'maida',          name:'Maida (All Purpose Flour)', unit:'1kg',      emoji:'🌾', cat:'grains',     basePrice:48  },
  { id:'suji',           name:'Suji (Semolina)',           unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:35  },
  { id:'besan',          name:'Besan (Gram Flour)',        unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:65  },
  { id:'dal_toor',       name:'Toor Dal',                 unit:'1kg',      emoji:'🫘', cat:'grains',     basePrice:135 },
  { id:'dal_moong',      name:'Moong Dal',                unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:95  },
  { id:'dal_chana',      name:'Chana Dal',                unit:'1kg',      emoji:'🫘', cat:'grains',     basePrice:110 },
  { id:'dal_masoor',     name:'Masoor Dal (Red Lentil)',   unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:85  },
  { id:'dal_urad',       name:'Urad Dal',                 unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:90  },
  { id:'kabuli_chana',   name:'Kabuli Chana',             unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:95  },
  { id:'rajma',          name:'Rajma (Kidney Beans)',      unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:90  },
  { id:'oats',           name:'Rolled Oats',              unit:'500g',     emoji:'🥣', cat:'grains',     basePrice:145 },
  { id:'quinoa',         name:'Quinoa',                   unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:280 },
  { id:'poha',           name:'Poha (Flattened Rice)',     unit:'500g',     emoji:'🍚', cat:'grains',     basePrice:45  },
  { id:'daliya',         name:'Broken Wheat (Daliya)',     unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:55  },
  { id:'bajra',          name:'Bajra Flour',              unit:'1kg',      emoji:'🌾', cat:'grains',     basePrice:65  },
  { id:'ragi',           name:'Ragi Flour',               unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:75  },
  { id:'pasta',          name:'Durum Wheat Pasta',         unit:'500g',     emoji:'🍝', cat:'grains',     basePrice:85  },

  // ——— SNACKS & PACKAGED FOOD ———
  { id:'lays_slt',       name:"Lay's Classic Salted",     unit:'73g',      emoji:'🍿', cat:'snacks',     basePrice:30  },
  { id:'lays_msa',       name:"Lay's Magic Masala",       unit:'73g',      emoji:'🍿', cat:'snacks',     basePrice:30  },
  { id:'kurkure',        name:'Kurkure Masala Munch',      unit:'90g',      emoji:'🍿', cat:'snacks',     basePrice:30  },
  { id:'uncle_chips',    name:'Uncle Chipps Spicy',        unit:'60g',      emoji:'🍿', cat:'snacks',     basePrice:20  },
  { id:'haldiram_bh',    name:'Haldiram Bhujia',           unit:'400g',     emoji:'🌶️', cat:'snacks',     basePrice:115 },
  { id:'haldiram_nm',    name:'Haldiram Mixed Namkeen',    unit:'400g',     emoji:'🌶️', cat:'snacks',     basePrice:95  },
  { id:'parle_g',        name:'Parle-G Biscuits',          unit:'800g',     emoji:'🍪', cat:'snacks',     basePrice:55  },
  { id:'bourbon',        name:'Bourbon Biscuits',          unit:'150g',     emoji:'🍪', cat:'snacks',     basePrice:25  },
  { id:'good_day',       name:'Good Day Cashew Biscuits',  unit:'150g',     emoji:'🍪', cat:'snacks',     basePrice:30  },
  { id:'oreo',           name:'Oreo Biscuits',             unit:'120g',     emoji:'🍪', cat:'snacks',     basePrice:45  },
  { id:'marie_gold',     name:'Marie Gold Biscuits',       unit:'250g',     emoji:'🍪', cat:'snacks',     basePrice:35  },
  { id:'cadbury_dm',     name:'Dairy Milk Silk',           unit:'150g',     emoji:'🍫', cat:'snacks',     basePrice:115 },
  { id:'kitkat',         name:'KitKat',                    unit:'37g',      emoji:'🍫', cat:'snacks',     basePrice:30  },
  { id:'5star',          name:'5 Star',                    unit:'40g',      emoji:'🍫', cat:'snacks',     basePrice:20  },
  { id:'maggi_noodle',   name:'Maggi 2-Minute Noodles',    unit:'280g',     emoji:'🍜', cat:'snacks',     basePrice:56  },
  { id:'yippee',         name:'Sunfeast Yippee Noodles',   unit:'240g',     emoji:'🍜', cat:'snacks',     basePrice:50  },
  { id:'popcorn',        name:'Act II Popcorn',            unit:'90g',      emoji:'🍿', cat:'snacks',     basePrice:45  },
  { id:'cornflakes',     name:"Kellogg's Cornflakes",      unit:'500g',     emoji:'🥣', cat:'snacks',     basePrice:175 },
  { id:'muesli',         name:'Muesli',                    unit:'400g',     emoji:'🥣', cat:'snacks',     basePrice:195 },
  { id:'rusk',           name:'Britannia Rusk',            unit:'400g',     emoji:'🍞', cat:'snacks',     basePrice:75  },
  { id:'bread_wh',       name:'Whole Wheat Bread',         unit:'400g',     emoji:'🍞', cat:'snacks',     basePrice:45  },
  { id:'bread_wt',       name:'White Bread',               unit:'400g',     emoji:'🍞', cat:'snacks',     basePrice:40  },
  { id:'pav',            name:'Pav Buns',                  unit:'6 pcs',    emoji:'🥖', cat:'snacks',     basePrice:35  },
  { id:'cashew',         name:'Cashew Nuts',               unit:'100g',     emoji:'🥜', cat:'snacks',     basePrice:120 },
  { id:'almonds',        name:'Almonds',                   unit:'100g',     emoji:'🥜', cat:'snacks',     basePrice:145 },
  { id:'walnut',         name:'Walnuts',                   unit:'100g',     emoji:'🥜', cat:'snacks',     basePrice:165 },
  { id:'raisins',        name:'Raisins (Kishmish)',         unit:'100g',     emoji:'🍇', cat:'snacks',     basePrice:55  },
  { id:'peanuts',        name:'Roasted Peanuts',           unit:'200g',     emoji:'🥜', cat:'snacks',     basePrice:45  },

  // ——— BEVERAGES ———
  { id:'water_1l',       name:'Bisleri Water',             unit:'1L',       emoji:'💧', cat:'beverages',  basePrice:20  },
  { id:'water_5l',       name:'Bisleri Water',             unit:'5L',       emoji:'💧', cat:'beverages',  basePrice:75  },
  { id:'juice_real',     name:'Real Fruit Juice Mixed',    unit:'1L',       emoji:'🧃', cat:'beverages',  basePrice:110 },
  { id:'juice_tp',       name:'Tropicana Orange Juice',    unit:'1L',       emoji:'🧃', cat:'beverages',  basePrice:120 },
  { id:'slice_mango',    name:'Slice Mango Drink',         unit:'600ml',    emoji:'🧃', cat:'beverages',  basePrice:35  },
  { id:'coke_2l',        name:'Coca Cola',                 unit:'2L',       emoji:'🥤', cat:'beverages',  basePrice:95  },
  { id:'pepsi_2l',       name:'Pepsi',                     unit:'2L',       emoji:'🥤', cat:'beverages',  basePrice:90  },
  { id:'sprite_2l',      name:'Sprite',                    unit:'2L',       emoji:'🥤', cat:'beverages',  basePrice:90  },
  { id:'thumbsup',       name:'Thums Up',                  unit:'750ml',    emoji:'🥤', cat:'beverages',  basePrice:40  },
  { id:'red_bull',       name:'Red Bull Energy Drink',     unit:'250ml',    emoji:'🥤', cat:'beverages',  basePrice:125 },
  { id:'tea_tata',       name:'Tata Tea Gold',             unit:'500g',     emoji:'🍵', cat:'beverages',  basePrice:285 },
  { id:'tea_rll',        name:'Brooke Bond Red Label',     unit:'250g',     emoji:'🍵', cat:'beverages',  basePrice:145 },
  { id:'tea_green',      name:'Green Tea Bags',            unit:'25 bags',  emoji:'🍵', cat:'beverages',  basePrice:130 },
  { id:'coffee_nescafe', name:'Nescafé Classic',           unit:'100g',     emoji:'☕', cat:'beverages',  basePrice:215 },
  { id:'coffee_bru',     name:'BRU Gold Coffee',           unit:'100g',     emoji:'☕', cat:'beverages',  basePrice:195 },
  { id:'horlicks',       name:'Horlicks Health Drink',     unit:'500g',     emoji:'🥛', cat:'beverages',  basePrice:295 },
  { id:'bournvita',      name:'Bournvita',                 unit:'500g',     emoji:'🥛', cat:'beverages',  basePrice:275 },
  { id:'coconut_water',  name:'Tender Coconut Water',      unit:'200ml',    emoji:'🥥', cat:'beverages',  basePrice:40  },
  { id:'lassi_pack',     name:'Amul Mango Lassi',          unit:'200ml',    emoji:'🥛', cat:'beverages',  basePrice:35  },

  // ——— COOKING ESSENTIALS ———
  { id:'oil_sunfl',      name:'Saffola Gold Oil',          unit:'1L',       emoji:'🫙', cat:'cooking',    basePrice:195 },
  { id:'oil_mustard',    name:'Mustard Oil',               unit:'1L',       emoji:'🫙', cat:'cooking',    basePrice:175 },
  { id:'oil_coconut',    name:'Coconut Oil',               unit:'500ml',    emoji:'🫙', cat:'cooking',    basePrice:155 },
  { id:'oil_olive',      name:'Olive Oil',                 unit:'500ml',    emoji:'🫙', cat:'cooking',    basePrice:395 },
  { id:'salt_tata',      name:'Tata Salt',                 unit:'1kg',      emoji:'🧂', cat:'cooking',    basePrice:28  },
  { id:'sugar_1kg',      name:'Sugar',                     unit:'1kg',      emoji:'🍬', cat:'cooking',    basePrice:45  },
  { id:'sugar_5kg',      name:'Sugar',                     unit:'5kg',      emoji:'🍬', cat:'cooking',    basePrice:210 },
  { id:'turmeric',       name:'Turmeric Powder (Haldi)',    unit:'100g',     emoji:'🟡', cat:'cooking',    basePrice:45  },
  { id:'chilli_pwd',     name:'Red Chilli Powder',         unit:'100g',     emoji:'🌶️', cat:'cooking',    basePrice:48  },
  { id:'coriander_pwd',  name:'Coriander Powder (Dhania)', unit:'100g',     emoji:'🟤', cat:'cooking',    basePrice:40  },
  { id:'cumin_seeds',    name:'Cumin Seeds (Jeera)',        unit:'100g',     emoji:'🌿', cat:'cooking',    basePrice:35  },
  { id:'mustard_seeds',  name:'Mustard Seeds (Rai)',        unit:'100g',     emoji:'⚫', cat:'cooking',    basePrice:25  },
  { id:'garam_masala',   name:'Garam Masala',              unit:'100g',     emoji:'🌶️', cat:'cooking',    basePrice:65  },
  { id:'chat_masala',    name:'Chaat Masala',              unit:'100g',     emoji:'🌶️', cat:'cooking',    basePrice:48  },
  { id:'biryani_masala', name:'Biryani Masala',            unit:'50g',      emoji:'🌶️', cat:'cooking',    basePrice:45  },
  { id:'tamarind',       name:'Tamarind (Imli)',            unit:'200g',     emoji:'🟤', cat:'cooking',    basePrice:35  },
  { id:'tomato_ketchup', name:'Maggi Tomato Ketchup',      unit:'500g',     emoji:'🍅', cat:'cooking',    basePrice:85  },
  { id:'mayo',           name:'Dr. Oetker Mayonnaise',     unit:'300g',     emoji:'🫙', cat:'cooking',    basePrice:115 },
  { id:'peanut_butter',  name:'Peanut Butter',             unit:'350g',     emoji:'🥜', cat:'cooking',    basePrice:195 },
  { id:'jam',            name:'Mixed Fruit Jam',           unit:'500g',     emoji:'🍓', cat:'cooking',    basePrice:110 },
  { id:'honey',          name:'Dabur Honey',               unit:'500g',     emoji:'🍯', cat:'cooking',    basePrice:235 },
  { id:'vinegar',        name:'White Vinegar',             unit:'500ml',    emoji:'🫙', cat:'cooking',    basePrice:55  },
  { id:'soy_sauce',      name:'Soy Sauce',                 unit:'200ml',    emoji:'🫙', cat:'cooking',    basePrice:65  },
  { id:'baking_soda',    name:'Baking Soda',               unit:'100g',     emoji:'⚪', cat:'cooking',    basePrice:35  },
  { id:'baking_powder',  name:'Baking Powder',             unit:'100g',     emoji:'⚪', cat:'cooking',    basePrice:45  },

  // ——— MEAT & SEAFOOD ———
  { id:'chicken_whole',  name:'Whole Chicken',             unit:'1kg',      emoji:'🍗', cat:'meat',       basePrice:195 },
  { id:'chicken_br',     name:'Chicken Breast',            unit:'500g',     emoji:'🍗', cat:'meat',       basePrice:155 },
  { id:'chicken_leg',    name:'Chicken Leg Pieces',        unit:'500g',     emoji:'🍗', cat:'meat',       basePrice:145 },
  { id:'mutton',         name:'Mutton (Goat)',              unit:'500g',     emoji:'🥩', cat:'meat',       basePrice:450 },
  { id:'fish_rohu',      name:'Rohu Fish',                 unit:'500g',     emoji:'🐟', cat:'meat',       basePrice:180 },
  { id:'fish_prawn',     name:'Prawns',                    unit:'250g',     emoji:'🦐', cat:'meat',       basePrice:220 },
  { id:'fish_pomfret',   name:'Pomfret Fish',              unit:'500g',     emoji:'🐡', cat:'meat',       basePrice:350 },
  { id:'chicken_sausage',name:'Chicken Sausage',           unit:'200g',     emoji:'🌭', cat:'meat',       basePrice:95  },
  { id:'chicken_nugget', name:'Chicken Nuggets',           unit:'400g',     emoji:'🍗', cat:'meat',       basePrice:245 },

  // ——— FROZEN FOODS ———
  { id:'frozen_peas',    name:'Frozen Green Peas',         unit:'500g',     emoji:'🟢', cat:'frozen',     basePrice:75  },
  { id:'frozen_corn',    name:'Frozen Sweet Corn',         unit:'500g',     emoji:'🌽', cat:'frozen',     basePrice:85  },
  { id:'frozen_fries',   name:'McCain French Fries',       unit:'420g',     emoji:'🍟', cat:'frozen',     basePrice:175 },
  { id:'frozen_pizza',   name:'Dr. Oetker Pizza',          unit:'310g',     emoji:'🍕', cat:'frozen',     basePrice:295 },
  { id:'ice_cream_vn',   name:'Amul Vanilla Ice Cream',    unit:'500ml',    emoji:'🍦', cat:'frozen',     basePrice:145 },
  { id:'ice_cream_ch',   name:'Amul Chocolate Ice Cream',  unit:'500ml',    emoji:'🍦', cat:'frozen',     basePrice:155 },
  { id:'kulfi',          name:'Matka Kulfi',               unit:'4 pcs',    emoji:'🍦', cat:'frozen',     basePrice:95  },
  { id:'idli_batter',    name:'Readymade Idli Batter',     unit:'1kg',      emoji:'🍚', cat:'frozen',     basePrice:85  },
  { id:'dosa_batter',    name:'Readymade Dosa Batter',     unit:'1kg',      emoji:'🫓', cat:'frozen',     basePrice:90  },
  { id:'paratha_frozen', name:'Frozen Aloo Paratha',       unit:'5 pcs',    emoji:'🫓', cat:'frozen',     basePrice:95  },

  // ——— PERSONAL CARE ———
  { id:'soap_dove',      name:'Dove Moisturising Soap',    unit:'100g',     emoji:'🧼', cat:'personal',   basePrice:48  },
  { id:'soap_dettol',    name:'Dettol Soap',               unit:'75g',      emoji:'🧼', cat:'personal',   basePrice:42  },
  { id:'soap_lux',       name:'Lux Soap',                  unit:'100g',     emoji:'🧼', cat:'personal',   basePrice:38  },
  { id:'shampoo_hns',    name:'Head & Shoulders Shampoo',  unit:'180ml',    emoji:'🧴', cat:'personal',   basePrice:195 },
  { id:'shampoo_dv',     name:'Dove Shampoo',              unit:'180ml',    emoji:'🧴', cat:'personal',   basePrice:185 },
  { id:'shampoo_ssl',    name:'Sunsilk Shampoo',           unit:'180ml',    emoji:'🧴', cat:'personal',   basePrice:155 },
  { id:'cond_dove',      name:'Dove Conditioner',          unit:'180ml',    emoji:'🧴', cat:'personal',   basePrice:195 },
  { id:'toothpaste_cl',  name:'Colgate MaxFresh',          unit:'150g',     emoji:'🦷', cat:'personal',   basePrice:92  },
  { id:'toothpaste_sn',  name:'Sensodyne Toothpaste',      unit:'70g',      emoji:'🦷', cat:'personal',   basePrice:165 },
  { id:'toothbrush',     name:'Oral-B Toothbrush',         unit:'1 pc',     emoji:'🪥', cat:'personal',   basePrice:55  },
  { id:'facewash_nv',    name:'Nivea Face Wash',           unit:'100ml',    emoji:'🧴', cat:'personal',   basePrice:155 },
  { id:'moisturiser',    name:'Nivea Body Lotion',         unit:'200ml',    emoji:'🧴', cat:'personal',   basePrice:175 },
  { id:'sunscreen',      name:'Lakme Sunscreen SPF 50',    unit:'50ml',     emoji:'🧴', cat:'personal',   basePrice:245 },
  { id:'deo_axe',        name:'Axe Deodorant',             unit:'150ml',    emoji:'💨', cat:'personal',   basePrice:195 },
  { id:'sanitizer',      name:'Dettol Hand Sanitizer',     unit:'200ml',    emoji:'🧴', cat:'personal',   basePrice:75  },
  { id:'cottonbuds',     name:'Cotton Buds',               unit:'100 pcs',  emoji:'🩹', cat:'personal',   basePrice:55  },
  { id:'razors',         name:'Gillette Razor',            unit:'2 pcs',    emoji:'🪒', cat:'personal',   basePrice:145 },
  { id:'pads',           name:'Stayfree Pads',             unit:'8 pcs',    emoji:'🩸', cat:'personal',   basePrice:68  },
  { id:'baby_lotion',    name:"Johnson's Baby Lotion",     unit:'200ml',    emoji:'🧴', cat:'personal',   basePrice:185 },

  // ——— HOUSEHOLD & CLEANING ———
  { id:'detergent_sf',   name:'Surf Excel Detergent',      unit:'1kg',      emoji:'🧺', cat:'household',  basePrice:200 },
  { id:'detergent_ar',   name:'Ariel Detergent',           unit:'1kg',      emoji:'🧺', cat:'household',  basePrice:235 },
  { id:'detergent_bar',  name:'Rin Detergent Bar',         unit:'250g',     emoji:'🧺', cat:'household',  basePrice:25  },
  { id:'fabric_sof',     name:'Comfort Fabric Softener',   unit:'800ml',    emoji:'🧺', cat:'household',  basePrice:175 },
  { id:'dishwash_vim',   name:'Vim Dishwash Liquid',       unit:'500ml',    emoji:'🍽️', cat:'household',  basePrice:85  },
  { id:'dishwash_prl',   name:'Pril Dishwash Gel',         unit:'500ml',    emoji:'🍽️', cat:'household',  basePrice:95  },
  { id:'dishwash_bar',   name:'Vim Dishwash Bar',          unit:'200g',     emoji:'🍽️', cat:'household',  basePrice:30  },
  { id:'floor_clean',    name:'Lizol Floor Cleaner',       unit:'1L',       emoji:'🫧', cat:'household',  basePrice:175 },
  { id:'toilet_clean',   name:'Harpic Toilet Cleaner',     unit:'750ml',    emoji:'🚽', cat:'household',  basePrice:155 },
  { id:'glass_clean',    name:'Colin Glass Cleaner',       unit:'500ml',    emoji:'🪟', cat:'household',  basePrice:115 },
  { id:'tissue_6r',      name:'Tissue Paper Rolls',        unit:'6 rolls',  emoji:'🧻', cat:'household',  basePrice:220 },
  { id:'tissue_12r',     name:'Tissue Paper Rolls',        unit:'12 rolls', emoji:'🧻', cat:'household',  basePrice:420 },
  { id:'garbage_bags',   name:'Garbage Bags',              unit:'30 pcs',   emoji:'🗑️', cat:'household',  basePrice:95  },
  { id:'aluminium_foil', name:'Aluminium Foil',            unit:'9m',       emoji:'✨', cat:'household',  basePrice:75  },
  { id:'air_freshener',  name:'Odonil Air Freshener',      unit:'50g',      emoji:'🌸', cat:'household',  basePrice:95  },
  { id:'mosquito_rep',   name:'Good Knight Refill',        unit:'45 nights',emoji:'🦟', cat:'household',  basePrice:85  },
  { id:'pest_spray',     name:'Mortein Spray',             unit:'425ml',    emoji:'🦟', cat:'household',  basePrice:195 },
  { id:'scrub_pad',      name:'Scotch-Brite Scrub Pad',    unit:'3 pcs',    emoji:'🧽', cat:'household',  basePrice:55  },
  { id:'gloves',         name:'Rubber Gloves',             unit:'1 pair',   emoji:'🧤', cat:'household',  basePrice:65  },

  // ——— BABY CARE ———
  { id:'diapers_sm',     name:'Pampers Baby Dry S',        unit:'20 pcs',   emoji:'👶', cat:'baby',       basePrice:280 },
  { id:'diapers_md',     name:'Pampers Baby Dry M',        unit:'18 pcs',   emoji:'👶', cat:'baby',       basePrice:295 },
  { id:'diapers_hub',    name:'Huggies Wonder Pants M',    unit:'30 pcs',   emoji:'👶', cat:'baby',       basePrice:495 },
  { id:'baby_food',      name:'Cerelac Wheat Rice',        unit:'300g',     emoji:'🍼', cat:'baby',       basePrice:255 },
  { id:'baby_wipes',     name:'Pampers Baby Wipes',        unit:'72 pcs',   emoji:'🧻', cat:'baby',       basePrice:245 },
  { id:'baby_powder',    name:"Johnson's Baby Powder",     unit:'200g',     emoji:'🌸', cat:'baby',       basePrice:175 },

  // ——— PET CARE ———
  { id:'dog_food',       name:'Pedigree Adult Dog Food',   unit:'1.2kg',    emoji:'🐕', cat:'petcare',    basePrice:395 },
  { id:'cat_food',       name:'Whiskas Cat Food',          unit:'500g',     emoji:'🐈', cat:'petcare',    basePrice:275 },
  { id:'pet_shampoo',    name:'Pet Shampoo',               unit:'200ml',    emoji:'🐾', cat:'petcare',    basePrice:185 },
  { id:'pet_treats',     name:'Pedigree Dog Treats',       unit:'90g',      emoji:'🦴', cat:'petcare',    basePrice:115 },
];

// ——— APP CONFIGURATIONS ———
const APPS = [
  {
    id: 'blinkit', name: 'Blinkit', emoji: '⚡', color: '#F8C200', textColor: '#000',
    eta: '8–12 min', priceMultiplier: { default: 1.00 }, freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 25 : 0,
    handlingFee:  ()    => 5,
    platformFee:  ()    => 5,
    smallOrderFee:(sub) => sub < 99  ? 15 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://blinkit.com/',
  },
  {
    id: 'zepto', name: 'Zepto', emoji: '🚀', color: '#FF3F6C', textColor: '#fff',
    eta: '10–15 min', priceMultiplier: { default: 0.98 }, freeDeliveryAbove: 149,
    deliveryFee:  (sub) => sub < 149 ? 30 : 0,
    handlingFee:  ()    => 2,
    platformFee:  ()    => 3,
    smallOrderFee:(sub) => sub < 79  ? 20 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Chennai'],
    deeplink: () => 'https://www.zeptonow.com/',
  },
  {
    id: 'swiggy_instamart', name: 'Instamart', emoji: '🟠', color: '#FC8019', textColor: '#fff',
    eta: '15–25 min', priceMultiplier: { default: 1.02 }, freeDeliveryAbove: 299,
    deliveryFee:  (sub) => sub < 299 ? 40 : 0,
    handlingFee:  ()    => 10,
    platformFee:  ()    => 5,
    smallOrderFee:()    => 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://www.swiggy.com/instamart',
  },
  {
    id: 'bigbasket_now', name: 'BB Now', emoji: '🟢', color: '#84C225', textColor: '#fff',
    eta: '10–20 min', priceMultiplier: { default: 1.01 }, freeDeliveryAbove: 249,
    deliveryFee:  (sub) => sub < 249 ? 35 : 0,
    handlingFee:  ()    => 0,
    platformFee:  ()    => 10,
    smallOrderFee:(sub) => sub < 99  ? 25 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Chennai','Kolkata'],
    deeplink: () => 'https://www.bigbasket.com/bbqinstant/',
  },
  {
    id: 'dunzo', name: 'Dunzo Daily', emoji: '🏪', color: '#00C5A2', textColor: '#fff',
    eta: '20–30 min', priceMultiplier: { default: 0.97 }, freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 20 : 0,
    handlingFee:  ()    => 5,
    platformFee:  ()    => 0,
    smallOrderFee:(sub) => sub < 99  ? 10 : 0,
    available: ['Mumbai','Delhi','Bangalore','Pune','Chennai','Hyderabad'],
    deeplink: () => 'https://www.dunzo.com/',
  },
  {
    id: 'jiomart', name: 'JioMart', emoji: '🔵', color: '#1A73E8', textColor: '#fff',
    eta: '2–4 hrs', priceMultiplier: { default: 0.95 }, freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 29 : 0,
    handlingFee:  ()    => 0,
    platformFee:  ()    => 0,
    smallOrderFee:()    => 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://www.jiomart.com/',
  },
];
