// ============================================================
//  QuickBasket — data.js
//  Product catalogue and app configurations
// ============================================================

const PRODUCTS = [
  // Dairy
  { id:'milk1',       name:'Full Cream Milk',       unit:'1L',    emoji:'🥛', cat:'dairy',     basePrice:68  },
  { id:'milk2',       name:'Toned Milk',             unit:'500ml', emoji:'🥛', cat:'dairy',     basePrice:35  },
  { id:'butter1',     name:'Amul Butter',            unit:'100g',  emoji:'🧈', cat:'dairy',     basePrice:58  },
  { id:'curd1',       name:'Fresh Curd',             unit:'400g',  emoji:'🫙', cat:'dairy',     basePrice:48  },
  { id:'cheese1',     name:'Processed Cheese',       unit:'200g',  emoji:'🧀', cat:'dairy',     basePrice:95  },
  { id:'paneer1',     name:'Fresh Paneer',           unit:'200g',  emoji:'🧀', cat:'dairy',     basePrice:85  },
  { id:'eggs1',       name:'Eggs',                   unit:'12 pcs',emoji:'🥚', cat:'dairy',     basePrice:89  },
  { id:'ghee1',       name:'Amul Pure Ghee',         unit:'500ml', emoji:'🧈', cat:'dairy',     basePrice:310 },
  // Fruits
  { id:'apple1',      name:'Apple (Shimla)',         unit:'1kg',   emoji:'🍎', cat:'fruits',    basePrice:180 },
  { id:'banana1',     name:'Banana',                 unit:'1 dozen',emoji:'🍌',cat:'fruits',   basePrice:45  },
  { id:'mango1',      name:'Alphonso Mango',         unit:'1kg',   emoji:'🥭', cat:'fruits',    basePrice:280 },
  { id:'orange1',     name:'Orange',                 unit:'1kg',   emoji:'🍊', cat:'fruits',    basePrice:90  },
  { id:'grapes1',     name:'Green Grapes',           unit:'500g',  emoji:'🍇', cat:'fruits',    basePrice:75  },
  { id:'watermelon1', name:'Watermelon',             unit:'1 pc',  emoji:'🍉', cat:'fruits',    basePrice:65  },
  // Vegetables
  { id:'tomato1',     name:'Tomato',                 unit:'1kg',   emoji:'🍅', cat:'vegetables',basePrice:40  },
  { id:'onion1',      name:'Onion',                  unit:'1kg',   emoji:'🧅', cat:'vegetables',basePrice:35  },
  { id:'potato1',     name:'Potato',                 unit:'1kg',   emoji:'🥔', cat:'vegetables',basePrice:30  },
  { id:'spinach1',    name:'Spinach',                unit:'250g',  emoji:'🌿', cat:'vegetables',basePrice:28  },
  { id:'carrot1',     name:'Carrot',                 unit:'500g',  emoji:'🥕', cat:'vegetables',basePrice:32  },
  { id:'broccoli1',   name:'Broccoli',               unit:'500g',  emoji:'🥦', cat:'vegetables',basePrice:68  },
  { id:'capsicum1',   name:'Capsicum',               unit:'500g',  emoji:'🫑', cat:'vegetables',basePrice:55  },
  // Grains
  { id:'rice1',       name:'Basmati Rice',           unit:'1kg',   emoji:'🍚', cat:'grains',    basePrice:120 },
  { id:'atta1',       name:'Wheat Flour (Atta)',     unit:'5kg',   emoji:'🌾', cat:'grains',    basePrice:245 },
  { id:'dal1',        name:'Toor Dal',               unit:'1kg',   emoji:'🫘', cat:'grains',    basePrice:135 },
  { id:'oats1',       name:'Rolled Oats',            unit:'500g',  emoji:'🥣', cat:'grains',    basePrice:145 },
  { id:'poha1',       name:'Poha (Flattened Rice)',  unit:'500g',  emoji:'🍚', cat:'grains',    basePrice:45  },
  // Snacks
  { id:'chips1',      name:"Lay's Classic Salted",  unit:'73g',   emoji:'🍿', cat:'snacks',    basePrice:30  },
  { id:'biscuit1',    name:'Parle-G',               unit:'800g',  emoji:'🍪', cat:'snacks',    basePrice:55  },
  { id:'namkeen1',    name:'Haldiram Namkeen',      unit:'400g',  emoji:'🌶️', cat:'snacks',    basePrice:95  },
  { id:'chocolate1',  name:'Dairy Milk Silk',       unit:'150g',  emoji:'🍫', cat:'snacks',    basePrice:115 },
  { id:'maggi1',      name:'Maggi Noodles',         unit:'280g',  emoji:'🍜', cat:'snacks',    basePrice:56  },
  // Beverages
  { id:'water1',      name:'Bisleri Water',         unit:'1L',    emoji:'💧', cat:'beverages', basePrice:20  },
  { id:'juice1',      name:'Real Fruit Juice',      unit:'1L',    emoji:'🧃', cat:'beverages', basePrice:110 },
  { id:'cola1',       name:'Coca Cola',             unit:'2L',    emoji:'🥤', cat:'beverages', basePrice:95  },
  { id:'tea1',        name:'Tata Tea Gold',         unit:'500g',  emoji:'🍵', cat:'beverages', basePrice:285 },
  { id:'coffee1',     name:'Nescafé Classic',       unit:'100g',  emoji:'☕', cat:'beverages', basePrice:215 },
  // Personal
  { id:'soap1',       name:'Dove Soap',             unit:'100g',  emoji:'🧼', cat:'personal',  basePrice:48  },
  { id:'shampoo1',    name:'Head & Shoulders',      unit:'180ml', emoji:'🧴', cat:'personal',  basePrice:195 },
  { id:'toothpaste1', name:'Colgate MaxFresh',      unit:'150g',  emoji:'🦷', cat:'personal',  basePrice:92  },
  { id:'sanitizer1',  name:'Hand Sanitizer',        unit:'200ml', emoji:'🧴', cat:'personal',  basePrice:75  },
  // Household
  { id:'detergent1',  name:'Surf Excel',            unit:'1kg',   emoji:'🧺', cat:'household', basePrice:200 },
  { id:'dishwash1',   name:'Vim Dishwash',          unit:'500ml', emoji:'🍽️', cat:'household', basePrice:85  },
  { id:'tissue1',     name:'Tissue Paper Rolls',    unit:'6 rolls',emoji:'🧻',cat:'household', basePrice:220 },
  { id:'freshener1',  name:'Odonil Air Freshener',  unit:'50g',   emoji:'🌸', cat:'household', basePrice:95  },
];

// ——— APP CONFIGURATIONS ———
// priceMultiplier: each app has slightly different pricing on items.
// Delivery/fees are calculated based on cart subtotal.
const APPS = [
  {
    id: 'blinkit',
    name: 'Blinkit',
    emoji: '⚡',
    color: '#F8C200',
    textColor: '#000',
    eta: '8–12 min',
    priceMultiplier: { default: 1.00 },
    freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 25 : 0,
    handlingFee:  ()    => 5,
    platformFee:  ()    => 5,
    smallOrderFee:(sub) => sub < 99  ? 15 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://blinkit.com/',
  },
  {
    id: 'zepto',
    name: 'Zepto',
    emoji: '🚀',
    color: '#FF3F6C',
    textColor: '#fff',
    eta: '10–15 min',
    priceMultiplier: { default: 0.98 },
    freeDeliveryAbove: 149,
    deliveryFee:  (sub) => sub < 149 ? 30 : 0,
    handlingFee:  ()    => 2,
    platformFee:  ()    => 3,
    smallOrderFee:(sub) => sub < 79  ? 20 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Chennai'],
    deeplink: () => 'https://www.zeptonow.com/',
  },
  {
    id: 'swiggy_instamart',
    name: 'Instamart',
    emoji: '🟠',
    color: '#FC8019',
    textColor: '#fff',
    eta: '15–25 min',
    priceMultiplier: { default: 1.02 },
    freeDeliveryAbove: 299,
    deliveryFee:  (sub) => sub < 299 ? 40 : 0,
    handlingFee:  ()    => 10,
    platformFee:  ()    => 5,
    smallOrderFee:()    => 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://www.swiggy.com/instamart',
  },
  {
    id: 'bigbasket_now',
    name: 'BB Now',
    emoji: '🟢',
    color: '#84C225',
    textColor: '#fff',
    eta: '10–20 min',
    priceMultiplier: { default: 1.01 },
    freeDeliveryAbove: 249,
    deliveryFee:  (sub) => sub < 249 ? 35 : 0,
    handlingFee:  ()    => 0,
    platformFee:  ()    => 10,
    smallOrderFee:(sub) => sub < 99  ? 25 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Chennai','Kolkata'],
    deeplink: () => 'https://www.bigbasket.com/bbqinstant/',
  },
  {
    id: 'dunzo',
    name: 'Dunzo Daily',
    emoji: '🏪',
    color: '#00C5A2',
    textColor: '#fff',
    eta: '20–30 min',
    priceMultiplier: { default: 0.97 },
    freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 20 : 0,
    handlingFee:  ()    => 5,
    platformFee:  ()    => 0,
    smallOrderFee:(sub) => sub < 99  ? 10 : 0,
    available: ['Mumbai','Delhi','Bangalore','Pune','Chennai','Hyderabad'],
    deeplink: () => 'https://www.dunzo.com/',
  },
  {
    id: 'jiomart',
    name: 'JioMart',
    emoji: '🔵',
    color: '#1A73E8',
    textColor: '#fff',
    eta: '2–4 hrs',
    priceMultiplier: { default: 0.95 },
    freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 29 : 0,
    handlingFee:  ()    => 0,
    platformFee:  ()    => 0,
    smallOrderFee:()    => 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://www.jiomart.com/',
  },
];
