// ============================================================
//  QuickBasket — data.js
//  Each product has: id, name, brand, unit, emoji, cat,
//  basePrice, tags[] — for rich search & brand comparison
// ============================================================

const PRODUCTS = [

  // ═══════════ DAIRY & EGGS ═══════════
  { id:'milk_amul_fc_1l',   name:'Full Cream Milk',    brand:'Amul',        unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:68,  tags:['doodh','dudh','milk','full cream','amul'] },
  { id:'milk_mother_fc_1l', name:'Full Cream Milk',    brand:'Mother Dairy',unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:66,  tags:['doodh','milk','mother dairy','full cream'] },
  { id:'milk_amul_tn_500',  name:'Toned Milk',         brand:'Amul',        unit:'500ml',    emoji:'🥛', cat:'dairy',      basePrice:35,  tags:['doodh','toned milk','amul'] },
  { id:'milk_oat_oatly',    name:'Oat Milk',           brand:'Oatly',       unit:'1L',       emoji:'🥛', cat:'dairy',      basePrice:299, tags:['oat milk','vegan milk','oatly'] },
  { id:'milk_almond_epig',  name:'Almond Milk',        brand:'Epigamia',    unit:'200ml',    emoji:'🥛', cat:'dairy',      basePrice:60,  tags:['almond milk','badam milk','epigamia','vegan'] },

  { id:'butter_amul_100',   name:'Butter',             brand:'Amul',        unit:'100g',     emoji:'🧈', cat:'dairy',      basePrice:58,  tags:['makhan','makkhan','butter','amul'] },
  { id:'butter_br_100',     name:'Butter',             brand:'Britannia',   unit:'100g',     emoji:'🧈', cat:'dairy',      basePrice:55,  tags:['makhan','butter','britannia'] },
  { id:'butter_amul_500',   name:'Butter',             brand:'Amul',        unit:'500g',     emoji:'🧈', cat:'dairy',      basePrice:265, tags:['makhan','butter','amul'] },

  { id:'curd_amul_200',     name:'Curd (Dahi)',         brand:'Amul',        unit:'200g',     emoji:'🫙', cat:'dairy',      basePrice:28,  tags:['dahi','curd','yogurt','amul'] },
  { id:'curd_amul_400',     name:'Curd (Dahi)',         brand:'Amul',        unit:'400g',     emoji:'🫙', cat:'dairy',      basePrice:48,  tags:['dahi','curd','yogurt','amul'] },
  { id:'curd_md_400',       name:'Curd (Dahi)',         brand:'Mother Dairy',unit:'400g',     emoji:'🫙', cat:'dairy',      basePrice:46,  tags:['dahi','curd','yogurt','mother dairy'] },
  { id:'curd_md_1kg',       name:'Curd (Dahi)',         brand:'Mother Dairy',unit:'1kg',      emoji:'🫙', cat:'dairy',      basePrice:90,  tags:['dahi','curd','yogurt','mother dairy'] },
  { id:'curd_greek_epi',    name:'Greek Yogurt',        brand:'Epigamia',    unit:'400g',     emoji:'🫙', cat:'dairy',      basePrice:130, tags:['greek yogurt','dahi','epigamia','curd'] },

  { id:'cheese_amul_200',   name:'Processed Cheese Slices',brand:'Amul',    unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:95,  tags:['cheese','processed cheese','amul'] },
  { id:'cheese_br_200',     name:'Processed Cheese',   brand:'Britannia',   unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:90,  tags:['cheese','processed cheese','britannia'] },
  { id:'cheese_spread_amul',name:'Cheese Spread',       brand:'Amul',        unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:92,  tags:['cheese spread','amul','cheese'] },

  { id:'paneer_amul_200',   name:'Paneer',             brand:'Amul',        unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:90,  tags:['paneer','panir','cottage cheese','amul'] },
  { id:'paneer_amul_500',   name:'Paneer',             brand:'Amul',        unit:'500g',     emoji:'🧀', cat:'dairy',      basePrice:210, tags:['paneer','panir','cottage cheese','amul'] },
  { id:'paneer_md_200',     name:'Paneer',             brand:'Mother Dairy',unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:85,  tags:['paneer','panir','cottage cheese','mother dairy'] },
  { id:'paneer_fresh_200',  name:'Fresh Paneer',        brand:'Local Farm',  unit:'200g',     emoji:'🧀', cat:'dairy',      basePrice:80,  tags:['paneer','panir','fresh paneer','cottage cheese'] },

  { id:'ghee_amul_500',     name:'Pure Ghee',          brand:'Amul',        unit:'500ml',    emoji:'🧈', cat:'dairy',      basePrice:310, tags:['ghee','amul','clarified butter'] },
  { id:'ghee_pat_500',      name:'Cow Ghee',            brand:'Patanjali',   unit:'500ml',    emoji:'🧈', cat:'dairy',      basePrice:275, tags:['ghee','patanjali','cow ghee','desi ghee'] },
  { id:'ghee_anik_500',     name:'Pure Ghee',          brand:'Anik',        unit:'500ml',    emoji:'🧈', cat:'dairy',      basePrice:295, tags:['ghee','anik'] },
  { id:'ghee_amul_1l',      name:'Pure Ghee',          brand:'Amul',        unit:'1L',       emoji:'🧈', cat:'dairy',      basePrice:590, tags:['ghee','amul'] },

  { id:'cream_amul_200',    name:'Fresh Cream',         brand:'Amul',        unit:'200ml',    emoji:'🍶', cat:'dairy',      basePrice:55,  tags:['cream','fresh cream','amul','malai'] },
  { id:'lassi_amul_200',    name:'Sweet Lassi',         brand:'Amul',        unit:'200ml',    emoji:'🥛', cat:'dairy',      basePrice:30,  tags:['lassi','sweet lassi','amul'] },
  { id:'buttermilk_amul',   name:'Buttermilk (Chaas)',  brand:'Amul',        unit:'500ml',    emoji:'🥛', cat:'dairy',      basePrice:28,  tags:['chaas','buttermilk','chhaas','amul'] },

  { id:'eggs_12_wt',        name:'White Eggs',          brand:'Suguna',      unit:'12 pcs',   emoji:'🥚', cat:'dairy',      basePrice:89,  tags:['anda','egg','eggs','white egg','suguna'] },
  { id:'eggs_6_br',         name:'Brown Eggs',          brand:'Country Delight',unit:'6 pcs', emoji:'🥚', cat:'dairy',      basePrice:62,  tags:['anda','egg','eggs','brown egg','country delight'] },
  { id:'eggs_12_org',       name:'Organic Eggs',        brand:'Organic India',unit:'12 pcs',  emoji:'🥚', cat:'dairy',      basePrice:145, tags:['anda','egg','eggs','organic egg','organic india'] },

  // ═══════════ FRUITS ═══════════
  { id:'apple_sh_1kg',      name:'Shimla Apple',        brand:'Fresh',       unit:'1kg',      emoji:'🍎', cat:'fruits',     basePrice:180, tags:['seb','apple','shimla apple','kashmiri apple'] },
  { id:'apple_fu_1kg',      name:'Fuji Apple',          brand:'Imported',    unit:'1kg',      emoji:'🍎', cat:'fruits',     basePrice:220, tags:['seb','apple','fuji apple'] },
  { id:'banana_1dz',        name:'Banana',              brand:'Fresh',       unit:'1 dozen',  emoji:'🍌', cat:'fruits',     basePrice:45,  tags:['kela','banana'] },
  { id:'mango_al_1kg',      name:'Alphonso Mango',      brand:'Ratnagiri',   unit:'1kg',      emoji:'🥭', cat:'fruits',     basePrice:280, tags:['aam','mango','alphonso','hapus','ratnagiri'] },
  { id:'mango_ke_1kg',      name:'Kesar Mango',         brand:'Gir',         unit:'1kg',      emoji:'🥭', cat:'fruits',     basePrice:220, tags:['aam','mango','kesar','gir kesar'] },
  { id:'orange_1kg',        name:'Orange (Nagpur)',      brand:'Fresh',       unit:'1kg',      emoji:'🍊', cat:'fruits',     basePrice:90,  tags:['santara','orange','nagpur orange','kinnow'] },
  { id:'mosambi_1kg',       name:'Mosambi',             brand:'Fresh',       unit:'1kg',      emoji:'🍋', cat:'fruits',     basePrice:75,  tags:['mosambi','sweet lime','citrus'] },
  { id:'lemon_6pc',         name:'Lemon',               brand:'Fresh',       unit:'6 pcs',    emoji:'🍋', cat:'fruits',     basePrice:25,  tags:['nimbu','lemon','lime'] },
  { id:'grapes_gr_500',     name:'Green Grapes',        brand:'Nashik',      unit:'500g',     emoji:'🍇', cat:'fruits',     basePrice:75,  tags:['angur','grapes','green grapes','nashik'] },
  { id:'grapes_bk_500',     name:'Black Grapes',        brand:'Fresh',       unit:'500g',     emoji:'🍇', cat:'fruits',     basePrice:80,  tags:['angur','grapes','black grapes','kali angur'] },
  { id:'watermelon',        name:'Watermelon',          brand:'Fresh',       unit:'1 pc (~2kg)',emoji:'🍉',cat:'fruits',     basePrice:65,  tags:['tarbooz','watermelon','tarbuj'] },
  { id:'pomegranate_1kg',   name:'Pomegranate',         brand:'Solapur',     unit:'1kg',      emoji:'🔴', cat:'fruits',     basePrice:160, tags:['anar','pomegranate','anaar'] },
  { id:'strawberry_200',    name:'Strawberry',          brand:'Fresh',       unit:'200g',     emoji:'🍓', cat:'fruits',     basePrice:95,  tags:['strawberry','sitafal'] },
  { id:'kiwi_4pc',          name:'Kiwi',                brand:'Imported',    unit:'4 pcs',    emoji:'🥝', cat:'fruits',     basePrice:120, tags:['kiwi'] },
  { id:'coconut_1pc',       name:'Coconut',             brand:'Fresh',       unit:'1 pc',     emoji:'🥥', cat:'fruits',     basePrice:45,  tags:['nariyal','coconut','nariyal'] },
  { id:'papaya_1pc',        name:'Papaya',              brand:'Fresh',       unit:'1 pc',     emoji:'🍈', cat:'fruits',     basePrice:55,  tags:['papita','papaya'] },
  { id:'guava_500',         name:'Guava',               brand:'Fresh',       unit:'500g',     emoji:'🍐', cat:'fruits',     basePrice:40,  tags:['amrood','guava'] },

  // ═══════════ VEGETABLES ═══════════
  { id:'tomato_1kg',        name:'Tomato',              brand:'Fresh',       unit:'1kg',      emoji:'🍅', cat:'vegetables', basePrice:40,  tags:['tamatar','tomato'] },
  { id:'onion_1kg',         name:'Onion',               brand:'Nashik',      unit:'1kg',      emoji:'🧅', cat:'vegetables', basePrice:35,  tags:['pyaaz','pyaz','onion','kanda'] },
  { id:'potato_1kg',        name:'Potato',              brand:'Fresh',       unit:'1kg',      emoji:'🥔', cat:'vegetables', basePrice:30,  tags:['aloo','alu','potato'] },
  { id:'spinach_250',       name:'Spinach (Palak)',      brand:'Fresh',       unit:'250g',     emoji:'🌿', cat:'vegetables', basePrice:28,  tags:['palak','spinach','saag'] },
  { id:'carrot_500',        name:'Carrot',              brand:'Fresh',       unit:'500g',     emoji:'🥕', cat:'vegetables', basePrice:32,  tags:['gajar','carrot'] },
  { id:'broccoli_500',      name:'Broccoli',            brand:'Fresh',       unit:'500g',     emoji:'🥦', cat:'vegetables', basePrice:68,  tags:['broccoli'] },
  { id:'capsicum_gr_500',   name:'Green Capsicum',      brand:'Fresh',       unit:'500g',     emoji:'🫑', cat:'vegetables', basePrice:55,  tags:['shimla mirchi','capsicum','green capsicum','bell pepper'] },
  { id:'capsicum_red_500',  name:'Red Capsicum',        brand:'Fresh',       unit:'500g',     emoji:'🌶️', cat:'vegetables', basePrice:85,  tags:['lal shimla mirchi','red capsicum','bell pepper'] },
  { id:'cauliflower_1pc',   name:'Cauliflower',         brand:'Fresh',       unit:'1 pc',     emoji:'🥦', cat:'vegetables', basePrice:45,  tags:['phool gobi','cauliflower','gobi'] },
  { id:'cabbage_1pc',       name:'Cabbage',             brand:'Fresh',       unit:'1 pc',     emoji:'🥬', cat:'vegetables', basePrice:35,  tags:['patta gobi','cabbage','band gobi'] },
  { id:'cucumber_500',      name:'Cucumber',            brand:'Fresh',       unit:'500g',     emoji:'🥒', cat:'vegetables', basePrice:28,  tags:['kheera','cucumber','kakdi'] },
  { id:'peas_500',          name:'Green Peas',          brand:'Fresh',       unit:'500g',     emoji:'🟢', cat:'vegetables', basePrice:55,  tags:['matar','green peas','peas'] },
  { id:'ladyfinger_500',    name:'Ladyfinger (Bhindi)',  brand:'Fresh',       unit:'500g',     emoji:'🌿', cat:'vegetables', basePrice:45,  tags:['bhindi','ladyfinger','okra'] },
  { id:'eggplant_500',      name:'Eggplant (Baingan)',   brand:'Fresh',       unit:'500g',     emoji:'🍆', cat:'vegetables', basePrice:35,  tags:['baingan','eggplant','brinjal','aubergine'] },
  { id:'garlic_100',        name:'Garlic',              brand:'Fresh',       unit:'100g',     emoji:'🧄', cat:'vegetables', basePrice:35,  tags:['lehsun','garlic','lasan'] },
  { id:'ginger_100',        name:'Ginger',              brand:'Fresh',       unit:'100g',     emoji:'🫚', cat:'vegetables', basePrice:20,  tags:['adrak','ginger','adrakh'] },
  { id:'greenchilli_100',   name:'Green Chilli',        brand:'Fresh',       unit:'100g',     emoji:'🌶️', cat:'vegetables', basePrice:15,  tags:['hari mirchi','green chilli','mirchi'] },
  { id:'mushroom_200',      name:'Button Mushroom',     brand:'Fresh',       unit:'200g',     emoji:'🍄', cat:'vegetables', basePrice:65,  tags:['mushroom','button mushroom','khumb'] },
  { id:'sweetcorn_2pc',     name:'Sweet Corn',          brand:'Fresh',       unit:'2 pcs',    emoji:'🌽', cat:'vegetables', basePrice:40,  tags:['bhutta','sweet corn','corn','makka'] },
  { id:'beetroot_500',      name:'Beetroot',            brand:'Fresh',       unit:'500g',     emoji:'🟣', cat:'vegetables', basePrice:42,  tags:['chukandar','beetroot','beet'] },
  { id:'coriander_50',      name:'Coriander (Dhania)',   brand:'Fresh',       unit:'50g',      emoji:'🌿', cat:'vegetables', basePrice:15,  tags:['dhania','coriander','cilantro','kothamalli'] },
  { id:'methi_250',         name:'Fenugreek (Methi)',    brand:'Fresh',       unit:'250g',     emoji:'🌿', cat:'vegetables', basePrice:22,  tags:['methi','fenugreek','venthayam'] },
  { id:'pudina_50',         name:'Mint (Pudina)',        brand:'Fresh',       unit:'50g',      emoji:'🌿', cat:'vegetables', basePrice:15,  tags:['pudina','mint','peppermint'] },

  // ═══════════ GRAINS, RICE & PULSES ═══════════
  { id:'rice_india_bsm_1',  name:'Basmati Rice',        brand:'India Gate',  unit:'1kg',      emoji:'🍚', cat:'grains',     basePrice:135, tags:['chawal','rice','basmati','india gate'] },
  { id:'rice_india_bsm_5',  name:'Basmati Rice',        brand:'India Gate',  unit:'5kg',      emoji:'🍚', cat:'grains',     basePrice:620, tags:['chawal','rice','basmati','india gate'] },
  { id:'rice_daawat_bsm_1', name:'Basmati Rice',        brand:'Daawat',      unit:'1kg',      emoji:'🍚', cat:'grains',     basePrice:125, tags:['chawal','rice','basmati','daawat'] },
  { id:'rice_daawat_bsm_5', name:'Basmati Rice',        brand:'Daawat',      unit:'5kg',      emoji:'🍚', cat:'grains',     basePrice:580, tags:['chawal','rice','basmati','daawat'] },
  { id:'rice_sona_5',       name:'Sona Masoori Rice',   brand:'24 Mantra',   unit:'5kg',      emoji:'🍚', cat:'grains',     basePrice:350, tags:['chawal','rice','sona masoori','24 mantra'] },
  { id:'rice_brown_1',      name:'Brown Rice',          brand:'Natureland',  unit:'1kg',      emoji:'🍚', cat:'grains',     basePrice:145, tags:['chawal','brown rice','natureland'] },

  { id:'atta_aash_5',       name:'Whole Wheat Atta',    brand:'Aashirvaad',  unit:'5kg',      emoji:'🌾', cat:'grains',     basePrice:265, tags:['aata','atta','wheat flour','aashirvaad'] },
  { id:'atta_aash_10',      name:'Whole Wheat Atta',    brand:'Aashirvaad',  unit:'10kg',     emoji:'🌾', cat:'grains',     basePrice:505, tags:['aata','atta','wheat flour','aashirvaad'] },
  { id:'atta_pil_5',        name:'Whole Wheat Atta',    brand:'Pillsbury',   unit:'5kg',      emoji:'🌾', cat:'grains',     basePrice:255, tags:['aata','atta','wheat flour','pillsbury'] },
  { id:'atta_pat_5',        name:'Whole Wheat Atta',    brand:'Patanjali',   unit:'5kg',      emoji:'🌾', cat:'grains',     basePrice:235, tags:['aata','atta','wheat flour','patanjali'] },
  { id:'maida_annapurna_1', name:'Maida',               brand:'Annapurna',   unit:'1kg',      emoji:'🌾', cat:'grains',     basePrice:48,  tags:['maida','all purpose flour','annapurna'] },
  { id:'suji_aash_500',     name:'Suji (Semolina)',      brand:'Aashirvaad',  unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:40,  tags:['suji','sooji','semolina','rawa','rava','aashirvaad'] },
  { id:'besan_rajdhani_500',name:'Besan (Gram Flour)',   brand:'Rajdhani',    unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:65,  tags:['besan','gram flour','chickpea flour','rajdhani'] },
  { id:'besan_nat_500',     name:'Besan (Gram Flour)',   brand:'Natureland',  unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:75,  tags:['besan','gram flour','chickpea flour','organic'] },

  { id:'dal_toor_tata_1',   name:'Toor Dal',            brand:'Tata Sampann',unit:'1kg',      emoji:'🫘', cat:'grains',     basePrice:145, tags:['toor dal','arhar dal','tata sampann','dal'] },
  { id:'dal_toor_nat_1',    name:'Toor Dal',            brand:'Natureland',  unit:'1kg',      emoji:'🫘', cat:'grains',     basePrice:165, tags:['toor dal','arhar dal','organic dal','natureland'] },
  { id:'dal_moong_500',     name:'Moong Dal (Split)',    brand:'Tata Sampann',unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:95,  tags:['moong dal','mung dal','tata sampann','dal'] },
  { id:'dal_masoor_500',    name:'Masoor Dal (Red)',     brand:'Tata Sampann',unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:85,  tags:['masoor dal','red lentil','lal masoor','tata sampann','dal'] },
  { id:'dal_chana_1',       name:'Chana Dal',           brand:'Tata Sampann',unit:'1kg',      emoji:'🫘', cat:'grains',     basePrice:110, tags:['chana dal','bengal gram','tata sampann','dal'] },
  { id:'dal_urad_500',      name:'Urad Dal (White)',     brand:'Tata Sampann',unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:90,  tags:['urad dal','black lentil','white lentil','tata sampann','dal'] },
  { id:'rajma_md_500',      name:'Rajma (Kidney Beans)', brand:'MDH',         unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:95,  tags:['rajma','kidney beans','mdh'] },
  { id:'kabuli_chana_500',  name:'Kabuli Chana',        brand:'Tata Sampann',unit:'500g',     emoji:'🫘', cat:'grains',     basePrice:95,  tags:['kabuli chana','chickpeas','chhole','tata sampann'] },

  { id:'oats_quaker_500',   name:'Oats',                brand:'Quaker',      unit:'500g',     emoji:'🥣', cat:'grains',     basePrice:155, tags:['oats','oatmeal','quaker','daliya'] },
  { id:'oats_saffola_500',  name:'Oats',                brand:'Saffola',     unit:'500g',     emoji:'🥣', cat:'grains',     basePrice:145, tags:['oats','oatmeal','saffola'] },
  { id:'poha_priya_500',    name:'Poha (Flattened Rice)',brand:'Priya',       unit:'500g',     emoji:'🍚', cat:'grains',     basePrice:48,  tags:['poha','flattened rice','beaten rice','chiwda'] },
  { id:'quinoa_org_500',    name:'Quinoa',              brand:'Organic India',unit:'500g',     emoji:'🌾', cat:'grains',     basePrice:285, tags:['quinoa','organic india'] },
  { id:'pasta_del_500',     name:'Penne Pasta',         brand:'Del Monte',   unit:'500g',     emoji:'🍝', cat:'grains',     basePrice:90,  tags:['pasta','penne','del monte','macaroni'] },
  { id:'pasta_bar_500',     name:'Fusilli Pasta',       brand:'Barilla',     unit:'500g',     emoji:'🍝', cat:'grains',     basePrice:120, tags:['pasta','fusilli','barilla'] },

  // ═══════════ SNACKS ═══════════
  { id:'lays_slt_73',       name:"Lay's Classic Salted", brand:"Lay's",      unit:'73g',      emoji:'🍿', cat:'snacks',     basePrice:30,  tags:['chips','lays','classic salted','crisps'] },
  { id:'lays_msa_73',       name:"Lay's Magic Masala",   brand:"Lay's",      unit:'73g',      emoji:'🍿', cat:'snacks',     basePrice:30,  tags:['chips','lays','magic masala'] },
  { id:'kurkure_90',        name:'Kurkure Masala Munch', brand:'Kurkure',    unit:'90g',      emoji:'🍿', cat:'snacks',     basePrice:30,  tags:['kurkure','masala munch','chips'] },
  { id:'haldiram_bh_400',   name:'Bhujia Sev',          brand:'Haldiram',    unit:'400g',     emoji:'🌶️', cat:'snacks',     basePrice:115, tags:['bhujia','sev','haldiram','namkeen'] },
  { id:'haldiram_nm_400',   name:'Aloo Bhujia',         brand:'Haldiram',    unit:'400g',     emoji:'🌶️', cat:'snacks',     basePrice:110, tags:['aloo bhujia','haldiram','namkeen'] },
  { id:'parle_g_800',       name:'Parle-G Biscuits',    brand:'Parle',       unit:'800g',     emoji:'🍪', cat:'snacks',     basePrice:55,  tags:['parle g','parleg','biscuit','glucose biscuit','parle'] },
  { id:'bourbon_100',       name:'Bourbon Biscuits',    brand:'Britannia',   unit:'150g',     emoji:'🍪', cat:'snacks',     basePrice:25,  tags:['bourbon','biscuit','britannia','chocolate biscuit'] },
  { id:'oreo_120',          name:'Oreo',                brand:'Cadbury',     unit:'120g',     emoji:'🍪', cat:'snacks',     basePrice:45,  tags:['oreo','biscuit','cadbury','cream biscuit'] },
  { id:'good_day_150',      name:'Good Day Cashew',     brand:'Britannia',   unit:'150g',     emoji:'🍪', cat:'snacks',     basePrice:30,  tags:['good day','biscuit','britannia','cashew biscuit'] },
  { id:'marie_250',         name:'Marie Gold',          brand:'Britannia',   unit:'250g',     emoji:'🍪', cat:'snacks',     basePrice:35,  tags:['marie gold','marie','britannia','biscuit'] },
  { id:'hide_seek_100',     name:'Hide & Seek',         brand:'Parle',       unit:'100g',     emoji:'🍪', cat:'snacks',     basePrice:30,  tags:['hide and seek','biscuit','parle','chocolate chip'] },

  { id:'dm_silk_150',       name:'Dairy Milk Silk',     brand:'Cadbury',     unit:'150g',     emoji:'🍫', cat:'snacks',     basePrice:115, tags:['dairy milk','silk','cadbury','chocolate'] },
  { id:'kitkat_37',         name:'KitKat',              brand:'Nestle',      unit:'37g',      emoji:'🍫', cat:'snacks',     basePrice:30,  tags:['kitkat','kit kat','nestle','chocolate','wafer'] },
  { id:'5star_40',          name:'5 Star',              brand:'Cadbury',     unit:'40g',      emoji:'🍫', cat:'snacks',     basePrice:20,  tags:['5 star','fivestar','cadbury','chocolate'] },
  { id:'dm_mini_180',       name:'Dairy Milk Miniatures',brand:'Cadbury',    unit:'180g',     emoji:'🍫', cat:'snacks',     basePrice:195, tags:['dairy milk','cadbury','chocolate','miniatures'] },
  { id:'kitkat_9pc',        name:'KitKat Slab',         brand:'Nestle',      unit:'9 fingers',emoji:'🍫', cat:'snacks',     basePrice:175, tags:['kitkat','nestle','chocolate'] },

  { id:'maggi_280',         name:'2-Minute Noodles',    brand:'Maggi',       unit:'280g',     emoji:'🍜', cat:'snacks',     basePrice:56,  tags:['maggi','noodles','instant noodles','2 minute'] },
  { id:'yippee_240',        name:'Yippee Noodles',      brand:'Sunfeast',    unit:'240g',     emoji:'🍜', cat:'snacks',     basePrice:50,  tags:['yippee','noodles','instant noodles','sunfeast','atta noodles'] },
  { id:'toprams_210',       name:'Top Ramen Curry',     brand:'Nissin',      unit:'210g',     emoji:'🍜', cat:'snacks',     basePrice:45,  tags:['top ramen','ramen','nissin','noodles'] },

  { id:'bread_bread_400',   name:'White Bread',         brand:'Britannia',   unit:'400g',     emoji:'🍞', cat:'snacks',     basePrice:40,  tags:['bread','white bread','sandwich bread','britannia'] },
  { id:'bread_moder_400',   name:'Whole Wheat Bread',   brand:'Modern',      unit:'400g',     emoji:'🍞', cat:'snacks',     basePrice:42,  tags:['bread','whole wheat bread','brown bread','modern'] },
  { id:'bread_hg_400',      name:'Multigrain Bread',    brand:'Harvest Gold',unit:'400g',     emoji:'🍞', cat:'snacks',     basePrice:50,  tags:['bread','multigrain bread','harvest gold'] },
  { id:'pav_6pc',           name:'Pav Buns',            brand:'Modern',      unit:'6 pcs',    emoji:'🥖', cat:'snacks',     basePrice:35,  tags:['pav','bun','dinner roll','modern'] },

  { id:'cornflakes_kel_500',name:'Cornflakes',          brand:"Kellogg's",   unit:'500g',     emoji:'🥣', cat:'snacks',     basePrice:175, tags:['cornflakes','corn flakes','kelloggs','breakfast cereal'] },
  { id:'muesli_kel_400',    name:'Muesli',              brand:"Kellogg's",   unit:'400g',     emoji:'🥣', cat:'snacks',     basePrice:195, tags:['muesli','granola','kelloggs','breakfast cereal'] },
  { id:'muesli_nt_400',     name:'Muesli',              brand:'Bagrry\'s',   unit:'400g',     emoji:'🥣', cat:'snacks',     basePrice:210, tags:['muesli','granola','bagrrys','breakfast cereal'] },

  { id:'cashew_100',        name:'Cashew (Kaju)',        brand:'Happilo',     unit:'100g',     emoji:'🥜', cat:'snacks',     basePrice:120, tags:['kaju','cashew','happilo','dry fruit'] },
  { id:'almond_100',        name:'Almonds (Badam)',      brand:'Happilo',     unit:'100g',     emoji:'🥜', cat:'snacks',     basePrice:145, tags:['badam','almonds','happilo','dry fruit'] },
  { id:'walnut_100',        name:'Walnuts (Akhrot)',     brand:'Happilo',     unit:'100g',     emoji:'🥜', cat:'snacks',     basePrice:165, tags:['akhrot','walnut','happilo','dry fruit'] },
  { id:'raisins_100',       name:'Raisins (Kishmish)',   brand:'Happilo',     unit:'100g',     emoji:'🍇', cat:'snacks',     basePrice:55,  tags:['kishmish','raisins','happilo','dry fruit','kismis'] },
  { id:'peanuts_200',       name:'Roasted Peanuts',      brand:'Bikano',      unit:'200g',     emoji:'🥜', cat:'snacks',     basePrice:45,  tags:['moongphali','peanuts','groundnut','bikano'] },

  // ═══════════ BEVERAGES ═══════════
  { id:'water_bisl_1l',     name:'Packaged Water',      brand:'Bisleri',     unit:'1L',       emoji:'💧', cat:'beverages',  basePrice:20,  tags:['paani','pani','water','bisleri'] },
  { id:'water_kinley_1l',   name:'Packaged Water',      brand:'Kinley',      unit:'1L',       emoji:'💧', cat:'beverages',  basePrice:18,  tags:['paani','water','kinley'] },
  { id:'water_bisl_5l',     name:'Packaged Water',      brand:'Bisleri',     unit:'5L',       emoji:'💧', cat:'beverages',  basePrice:75,  tags:['paani','water','bisleri'] },

  { id:'juice_real_1l',     name:'Mixed Fruit Juice',   brand:'Real',        unit:'1L',       emoji:'🧃', cat:'beverages',  basePrice:110, tags:['juice','fruit juice','real','mixed fruit'] },
  { id:'juice_tp_1l',       name:'Orange Juice',        brand:'Tropicana',   unit:'1L',       emoji:'🧃', cat:'beverages',  basePrice:120, tags:['juice','orange juice','tropicana'] },
  { id:'slice_600',         name:'Mango Drink',         brand:'Slice',       unit:'600ml',    emoji:'🧃', cat:'beverages',  basePrice:35,  tags:['mango drink','slice','aamras'] },
  { id:'frooti_200',        name:'Mango Drink',         brand:'Frooti',      unit:'200ml',    emoji:'🧃', cat:'beverages',  basePrice:18,  tags:['frooti','mango drink','parle agro'] },

  { id:'coke_2l',           name:'Coca Cola',           brand:'Coca-Cola',   unit:'2L',       emoji:'🥤', cat:'beverages',  basePrice:95,  tags:['coke','coca cola','cold drink','soft drink'] },
  { id:'pepsi_2l',          name:'Pepsi',               brand:'PepsiCo',     unit:'2L',       emoji:'🥤', cat:'beverages',  basePrice:90,  tags:['pepsi','cold drink','soft drink'] },
  { id:'sprite_2l',         name:'Sprite',              brand:'Coca-Cola',   unit:'2L',       emoji:'🥤', cat:'beverages',  basePrice:90,  tags:['sprite','limca','cold drink','lemon soda'] },
  { id:'thumbsup_750',      name:'Thums Up',            brand:'Coca-Cola',   unit:'750ml',    emoji:'🥤', cat:'beverages',  basePrice:40,  tags:['thums up','thumbs up','cold drink'] },
  { id:'redbull_250',       name:'Energy Drink',        brand:'Red Bull',    unit:'250ml',    emoji:'🥤', cat:'beverages',  basePrice:125, tags:['red bull','energy drink','redbull'] },
  { id:'monster_355',       name:'Energy Drink',        brand:'Monster',     unit:'355ml',    emoji:'🥤', cat:'beverages',  basePrice:120, tags:['monster','energy drink'] },

  { id:'tea_tata_500',      name:'Premium Tea',         brand:'Tata Tea Gold',unit:'500g',    emoji:'🍵', cat:'beverages',  basePrice:285, tags:['chai','tea','tata tea','tata tea gold'] },
  { id:'tea_br_250',        name:'Red Label Tea',       brand:'Brooke Bond',  unit:'250g',    emoji:'🍵', cat:'beverages',  basePrice:145, tags:['chai','tea','red label','brooke bond'] },
  { id:'tea_taj_250',       name:'Premium Tea',         brand:'Taj Mahal',    unit:'250g',    emoji:'🍵', cat:'beverages',  basePrice:195, tags:['chai','tea','taj mahal','brooke bond'] },
  { id:'tea_green_25',      name:'Green Tea Bags',      brand:'Lipton',       unit:'25 bags', emoji:'🍵', cat:'beverages',  basePrice:130, tags:['green tea','lipton','herbal tea'] },
  { id:'tea_green_tvn',     name:'Green Tea Bags',      brand:'Tetley',       unit:'25 bags', emoji:'🍵', cat:'beverages',  basePrice:145, tags:['green tea','tetley','herbal tea'] },

  { id:'coffee_nescafe_100',name:'Instant Coffee',      brand:'Nescafé',      unit:'100g',    emoji:'☕', cat:'beverages',  basePrice:215, tags:['coffee','nescafe','nescafé','instant coffee'] },
  { id:'coffee_bru_100',    name:'Gold Coffee',         brand:'BRU',          unit:'100g',    emoji:'☕', cat:'beverages',  basePrice:195, tags:['coffee','bru','instant coffee'] },
  { id:'coffee_cont_50',    name:'Instant Coffee',      brand:'Continental',  unit:'50g',     emoji:'☕', cat:'beverages',  basePrice:175, tags:['coffee','continental','filter coffee'] },

  { id:'horlicks_500',      name:'Health Drink',        brand:'Horlicks',     unit:'500g',    emoji:'🥛', cat:'beverages',  basePrice:295, tags:['horlicks','health drink','malt drink','bournvita'] },
  { id:'bournvita_500',     name:'Health Drink',        brand:'Bournvita',    unit:'500g',    emoji:'🥛', cat:'beverages',  basePrice:275, tags:['bournvita','health drink','chocolate drink','cadbury'] },
  { id:'complan_500',       name:'Health Drink',        brand:'Complan',      unit:'500g',    emoji:'🥛', cat:'beverages',  basePrice:325, tags:['complan','health drink','protein drink'] },
  { id:'coconut_water_200', name:'Tender Coconut Water',brand:'Raw Pressery', unit:'200ml',   emoji:'🥥', cat:'beverages',  basePrice:45,  tags:['coconut water','nariyal paani','raw pressery'] },

  // ═══════════ COOKING ESSENTIALS ═══════════
  { id:'oil_saffola_1l',    name:'Refined Oil',         brand:'Saffola Gold', unit:'1L',      emoji:'🫙', cat:'cooking',    basePrice:195, tags:['tel','oil','saffola','refined oil','sunflower oil'] },
  { id:'oil_fortune_1l',    name:'Sunflower Oil',       brand:'Fortune',      unit:'1L',      emoji:'🫙', cat:'cooking',    basePrice:180, tags:['tel','oil','fortune','sunflower oil'] },
  { id:'oil_mustard_1l',    name:'Mustard Oil',         brand:'Dhara',        unit:'1L',      emoji:'🫙', cat:'cooking',    basePrice:175, tags:['sarson tel','mustard oil','dhara'] },
  { id:'oil_coconut_500',   name:'Coconut Oil',         brand:'Parachute',    unit:'500ml',   emoji:'🫙', cat:'cooking',    basePrice:155, tags:['coconut oil','nariyal tel','parachute'] },
  { id:'oil_olive_ber_500', name:'Olive Oil',           brand:'Bertolli',     unit:'500ml',   emoji:'🫙', cat:'cooking',    basePrice:395, tags:['olive oil','bertolli','jaitun ka tel'] },
  { id:'oil_olive_divo_500',name:'Extra Virgin Olive Oil',brand:'DiVo',       unit:'500ml',   emoji:'🫙', cat:'cooking',    basePrice:360, tags:['olive oil','extra virgin','divo'] },

  { id:'salt_tata_1',       name:'Iodised Salt',        brand:'Tata Salt',    unit:'1kg',     emoji:'🧂', cat:'cooking',    basePrice:28,  tags:['namak','salt','tata salt','iodised salt'] },
  { id:'salt_capt_1',       name:'Rock Salt (Sendha)',   brand:'Captain Cook', unit:'1kg',     emoji:'🧂', cat:'cooking',    basePrice:32,  tags:['namak','salt','rock salt','sendha namak'] },
  { id:'sugar_1kg',         name:'Sugar',               brand:'Madhur',       unit:'1kg',     emoji:'🍬', cat:'cooking',    basePrice:45,  tags:['cheeni','chini','sugar','madhur'] },
  { id:'sugar_5kg',         name:'Sugar',               brand:'Madhur',       unit:'5kg',     emoji:'🍬', cat:'cooking',    basePrice:210, tags:['cheeni','chini','sugar','madhur'] },

  { id:'turmeric_everest_100',name:'Turmeric Powder',   brand:'Everest',      unit:'100g',    emoji:'🟡', cat:'cooking',    basePrice:48,  tags:['haldi','turmeric','haldi powder','everest'] },
  { id:'turmeric_mdh_100',  name:'Turmeric Powder',     brand:'MDH',          unit:'100g',    emoji:'🟡', cat:'cooking',    basePrice:45,  tags:['haldi','turmeric','haldi powder','mdh'] },
  { id:'chilli_ev_100',     name:'Red Chilli Powder',   brand:'Everest',      unit:'100g',    emoji:'🌶️', cat:'cooking',    basePrice:55,  tags:['mirchi powder','lal mirchi','red chilli','everest'] },
  { id:'chilli_mdh_100',    name:'Red Chilli Powder',   brand:'MDH',          unit:'100g',    emoji:'🌶️', cat:'cooking',    basePrice:48,  tags:['mirchi powder','lal mirchi','red chilli','mdh'] },
  { id:'garam_masala_ev_50',name:'Garam Masala',        brand:'Everest',      unit:'50g',     emoji:'🌶️', cat:'cooking',    basePrice:48,  tags:['garam masala','masala','everest'] },
  { id:'garam_masala_mdh_50',name:'Garam Masala',       brand:'MDH',          unit:'50g',     emoji:'🌶️', cat:'cooking',    basePrice:45,  tags:['garam masala','masala','mdh'] },
  { id:'cumin_ev_100',      name:'Cumin Seeds (Jeera)', brand:'Everest',      unit:'100g',    emoji:'🌿', cat:'cooking',    basePrice:38,  tags:['jeera','cumin','jeera seeds','everest'] },
  { id:'coriander_ev_100',  name:'Coriander Powder',    brand:'Everest',      unit:'100g',    emoji:'🟤', cat:'cooking',    basePrice:42,  tags:['dhania powder','coriander powder','everest'] },
  { id:'biryani_shan_50',   name:'Biryani Masala',      brand:'Shan',         unit:'50g',     emoji:'🌶️', cat:'cooking',    basePrice:55,  tags:['biryani masala','shan','biryani'] },
  { id:'biryani_ev_50',     name:'Biryani Masala',      brand:'Everest',      unit:'50g',     emoji:'🌶️', cat:'cooking',    basePrice:48,  tags:['biryani masala','everest','biryani'] },
  { id:'chicken_mdh_50',    name:'Chicken Masala',      brand:'MDH',          unit:'50g',     emoji:'🌶️', cat:'cooking',    basePrice:42,  tags:['chicken masala','mdh','masala'] },

  { id:'ketchup_maggi_500', name:'Tomato Ketchup',      brand:'Maggi',        unit:'500g',    emoji:'🍅', cat:'cooking',    basePrice:85,  tags:['ketchup','tomato sauce','maggi','tamatar sauce'] },
  { id:'ketchup_kissan_500',name:'Tomato Ketchup',      brand:'Kissan',       unit:'500g',    emoji:'🍅', cat:'cooking',    basePrice:80,  tags:['ketchup','tomato sauce','kissan'] },
  { id:'mayo_dr_300',       name:'Mayonnaise',          brand:'Dr. Oetker',   unit:'300g',    emoji:'🫙', cat:'cooking',    basePrice:115, tags:['mayo','mayonnaise','dr oetker'] },
  { id:'mayo_fun_300',      name:'Eggless Mayonnaise',  brand:'Fun Foods',    unit:'300g',    emoji:'🫙', cat:'cooking',    basePrice:95,  tags:['mayo','eggless mayo','fun foods','veg mayo'] },
  { id:'pb_sf_350',         name:'Peanut Butter',       brand:'Sundrop',      unit:'350g',    emoji:'🥜', cat:'cooking',    basePrice:185, tags:['peanut butter','moongphali butter','sundrop'] },
  { id:'pb_myfitness_500',  name:'Natural Peanut Butter',brand:'MyfitnessPal',unit:'500g',    emoji:'🥜', cat:'cooking',    basePrice:245, tags:['peanut butter','natural peanut butter','myfitnesspal','protein'] },
  { id:'jam_kissan_500',    name:'Mixed Fruit Jam',     brand:'Kissan',       unit:'500g',    emoji:'🍓', cat:'cooking',    basePrice:110, tags:['jam','fruit jam','kissan','mixed fruit jam'] },
  { id:'honey_dabur_500',   name:'Pure Honey',          brand:'Dabur',        unit:'500g',    emoji:'🍯', cat:'cooking',    basePrice:235, tags:['honey','madhu','dabur','pure honey'] },
  { id:'honey_pat_500',     name:'Pure Honey',          brand:'Patanjali',    unit:'500g',    emoji:'🍯', cat:'cooking',    basePrice:195, tags:['honey','madhu','patanjali'] },

  // ═══════════ MEAT & SEAFOOD ═══════════
  { id:'chicken_whole_1',   name:'Whole Chicken',       brand:'Licious',      unit:'1kg',     emoji:'🍗', cat:'meat',       basePrice:215, tags:['murga','chicken','whole chicken','licious'] },
  { id:'chicken_br_500',    name:'Chicken Breast',      brand:'Licious',      unit:'500g',    emoji:'🍗', cat:'meat',       basePrice:165, tags:['chicken breast','murga','boneless chicken','licious'] },
  { id:'chicken_leg_500',   name:'Chicken Leg Pieces',  brand:'Licious',      unit:'500g',    emoji:'🍗', cat:'meat',       basePrice:155, tags:['chicken leg','murga','leg piece','licious'] },
  { id:'mutton_500',        name:'Mutton (Goat)',        brand:'Licious',      unit:'500g',    emoji:'🥩', cat:'meat',       basePrice:465, tags:['mutton','gosht','goat meat','lamb','licious'] },
  { id:'prawn_250',         name:'Prawns (Medium)',      brand:'Licious',      unit:'250g',    emoji:'🦐', cat:'meat',       basePrice:235, tags:['prawn','jhinga','jheenga','shrimp','licious'] },
  { id:'fish_rohu_500',     name:'Rohu Fish',           brand:'Fresh',        unit:'500g',    emoji:'🐟', cat:'meat',       basePrice:185, tags:['machli','fish','rohu','rui'] },
  { id:'chicken_sausage_200',name:'Chicken Sausage',    brand:'Godrej Yummiez',unit:'200g',   emoji:'🌭', cat:'meat',       basePrice:95,  tags:['sausage','chicken sausage','godrej yummiez'] },
  { id:'chicken_nugget_400',name:'Chicken Nuggets',     brand:'Godrej Yummiez',unit:'400g',   emoji:'🍗', cat:'meat',       basePrice:250, tags:['nugget','chicken nuggets','godrej yummiez'] },

  // ═══════════ FROZEN FOODS ═══════════
  { id:'frozen_peas_500',   name:'Frozen Green Peas',   brand:'McCain',       unit:'500g',    emoji:'🟢', cat:'frozen',     basePrice:75,  tags:['matar','peas','frozen peas','mccain'] },
  { id:'frozen_fries_mcc',  name:'French Fries',        brand:'McCain',       unit:'420g',    emoji:'🍟', cat:'frozen',     basePrice:175, tags:['french fries','frozen fries','mccain','aloo'] },
  { id:'frozen_pizza_dr',   name:'Margherita Pizza',    brand:'Dr. Oetker',   unit:'310g',    emoji:'🍕', cat:'frozen',     basePrice:295, tags:['pizza','margherita','dr oetker','frozen pizza'] },
  { id:'ice_cream_amul_vn', name:'Vanilla Ice Cream',   brand:'Amul',         unit:'500ml',   emoji:'🍦', cat:'frozen',     basePrice:145, tags:['ice cream','vanilla ice cream','amul','gelato'] },
  { id:'ice_cream_amul_ch', name:'Chocolate Ice Cream', brand:'Amul',         unit:'500ml',   emoji:'🍦', cat:'frozen',     basePrice:155, tags:['ice cream','chocolate ice cream','amul'] },
  { id:'kulfi_4pc',         name:'Matka Kulfi',         brand:'Havmor',       unit:'4 pcs',   emoji:'🍦', cat:'frozen',     basePrice:95,  tags:['kulfi','matka kulfi','havmor','ice cream'] },
  { id:'idli_batter_1',     name:'Idli Batter',         brand:'id.freshFood', unit:'1kg',     emoji:'🍚', cat:'frozen',     basePrice:85,  tags:['idli batter','ready batter','id fresh'] },
  { id:'dosa_batter_1',     name:'Dosa Batter',         brand:'id.freshFood', unit:'1kg',     emoji:'🫓', cat:'frozen',     basePrice:90,  tags:['dosa batter','ready batter','id fresh'] },
  { id:'paratha_frz_5',     name:'Aloo Paratha',        brand:'Kawan',        unit:'5 pcs',   emoji:'🫓', cat:'frozen',     basePrice:115, tags:['paratha','aloo paratha','frozen paratha','kawan'] },

  // ═══════════ PERSONAL CARE ═══════════
  { id:'soap_dove_100',     name:'Moisturising Bar',    brand:'Dove',         unit:'100g',    emoji:'🧼', cat:'personal',   basePrice:48,  tags:['sabun','soap','dove','bathing bar'] },
  { id:'soap_dettol_75',    name:'Antibacterial Soap',  brand:'Dettol',       unit:'75g',     emoji:'🧼', cat:'personal',   basePrice:42,  tags:['sabun','soap','dettol','antibacterial soap'] },
  { id:'soap_lux_100',      name:'Beauty Soap',         brand:'Lux',          unit:'100g',    emoji:'🧼', cat:'personal',   basePrice:38,  tags:['sabun','soap','lux','beauty soap'] },
  { id:'soap_pears_75',     name:'Transparent Soap',    brand:'Pears',        unit:'75g',     emoji:'🧼', cat:'personal',   basePrice:58,  tags:['sabun','soap','pears'] },
  { id:'soap_santoor_100',  name:'Sandalwood Soap',     brand:'Santoor',      unit:'100g',    emoji:'🧼', cat:'personal',   basePrice:38,  tags:['sabun','soap','santoor','chandan soap'] },

  { id:'shampoo_hns_180',   name:'Anti-Dandruff Shampoo',brand:'Head & Shoulders',unit:'180ml',emoji:'🧴',cat:'personal',  basePrice:195, tags:['shampoo','head and shoulders','h&s','anti dandruff'] },
  { id:'shampoo_dv_180',    name:'Intensive Shampoo',   brand:'Dove',         unit:'180ml',   emoji:'🧴', cat:'personal',   basePrice:185, tags:['shampoo','dove'] },
  { id:'shampoo_ssl_180',   name:'Shampoo',             brand:'Sunsilk',      unit:'180ml',   emoji:'🧴', cat:'personal',   basePrice:155, tags:['shampoo','sunsilk'] },
  { id:'shampoo_tre_180',   name:'Smooth & Shine Shampoo',brand:'TRESemmé',   unit:'180ml',   emoji:'🧴', cat:'personal',   basePrice:175, tags:['shampoo','tresemme','tresemmé'] },
  { id:'cond_dove_180',     name:'Conditioner',         brand:'Dove',         unit:'180ml',   emoji:'🧴', cat:'personal',   basePrice:195, tags:['conditioner','hair conditioner','dove'] },

  { id:'toothpaste_cl_150', name:'MaxFresh Toothpaste', brand:'Colgate',      unit:'150g',    emoji:'🦷', cat:'personal',   basePrice:92,  tags:['toothpaste','colgate','tooth paste','colgate maxfresh'] },
  { id:'toothpaste_sn_70',  name:'Toothpaste',          brand:'Sensodyne',    unit:'70g',     emoji:'🦷', cat:'personal',   basePrice:165, tags:['toothpaste','sensodyne','sensitive teeth'] },
  { id:'toothpaste_pt_200', name:'Dant Kanti Toothpaste',brand:'Patanjali',   unit:'200g',    emoji:'🦷', cat:'personal',   basePrice:65,  tags:['toothpaste','patanjali','dant kanti','herbal toothpaste'] },
  { id:'toothpaste_cl_pep', name:'Strong Teeth Toothpaste',brand:'Colgate',   unit:'200g',    emoji:'🦷', cat:'personal',   basePrice:115, tags:['toothpaste','colgate','strong teeth'] },
  { id:'toothbrush_oral_1', name:'Toothbrush',          brand:'Oral-B',       unit:'1 pc',    emoji:'🪥', cat:'personal',   basePrice:55,  tags:['toothbrush','oral b','oral-b','dant brush'] },

  { id:'facewash_nv_100',   name:'Face Wash',           brand:'Nivea',        unit:'100ml',   emoji:'🧴', cat:'personal',   basePrice:155, tags:['face wash','facewash','nivea'] },
  { id:'facewash_garnier',  name:'Bright & Clean Face Wash',brand:'Garnier',  unit:'100ml',   emoji:'🧴', cat:'personal',   basePrice:145, tags:['face wash','facewash','garnier'] },
  { id:'moisturiser_nv_200',name:'Body Lotion',         brand:'Nivea',        unit:'200ml',   emoji:'🧴', cat:'personal',   basePrice:175, tags:['moisturiser','body lotion','nivea','lotion'] },
  { id:'sunscreen_50',      name:'Sunscreen SPF 50',    brand:'Lakme',        unit:'50ml',    emoji:'🧴', cat:'personal',   basePrice:245, tags:['sunscreen','spf','lakme','sunblock'] },
  { id:'deo_axe_150',       name:'Deodorant Spray',     brand:'Axe',          unit:'150ml',   emoji:'💨', cat:'personal',   basePrice:195, tags:['deo','deodorant','axe','perfume'] },
  { id:'deo_nv_50',         name:'Deodorant Roll-On',   brand:'Nivea',        unit:'50ml',    emoji:'💨', cat:'personal',   basePrice:175, tags:['deo','deodorant roll on','nivea'] },
  { id:'sanitizer_200',     name:'Hand Sanitizer',      brand:'Dettol',       unit:'200ml',   emoji:'🧴', cat:'personal',   basePrice:75,  tags:['sanitizer','hand sanitizer','dettol','hand wash'] },
  { id:'handwash_dettol',   name:'Hand Wash',           brand:'Dettol',       unit:'250ml',   emoji:'🧴', cat:'personal',   basePrice:85,  tags:['hand wash','handwash','dettol','soap'] },
  { id:'razors_gillette_2', name:'Shaving Razor',       brand:'Gillette',     unit:'2 pcs',   emoji:'🪒', cat:'personal',   basePrice:145, tags:['razor','shaving','gillette','shave'] },
  { id:'pads_stayfree_8',   name:'Sanitary Pads',       brand:'Stayfree',     unit:'8 pcs',   emoji:'🩸', cat:'personal',   basePrice:68,  tags:['pads','sanitary pads','stayfree','whisper'] },
  { id:'pads_whisper_8',    name:'Sanitary Pads',       brand:'Whisper',      unit:'8 pcs',   emoji:'🩸', cat:'personal',   basePrice:72,  tags:['pads','sanitary pads','whisper','stayfree'] },

  // ═══════════ HOUSEHOLD ═══════════
  { id:'detergent_surf_1',  name:'Washing Powder',      brand:'Surf Excel',   unit:'1kg',     emoji:'🧺', cat:'household',  basePrice:200, tags:['detergent','washing powder','surf excel','kapde dhona'] },
  { id:'detergent_ariel_1', name:'Washing Powder',      brand:'Ariel',        unit:'1kg',     emoji:'🧺', cat:'household',  basePrice:235, tags:['detergent','washing powder','ariel'] },
  { id:'detergent_tide_1',  name:'Washing Powder',      brand:'Tide',         unit:'1kg',     emoji:'🧺', cat:'household',  basePrice:195, tags:['detergent','washing powder','tide'] },
  { id:'detergent_bar_rin', name:'Detergent Bar',       brand:'Rin',          unit:'250g',    emoji:'🧺', cat:'household',  basePrice:25,  tags:['detergent bar','rin','washing bar'] },
  { id:'fabric_comfort_800',name:'Fabric Softener',     brand:'Comfort',      unit:'800ml',   emoji:'🧺', cat:'household',  basePrice:175, tags:['fabric softener','comfort','fabric conditioner'] },

  { id:'dishwash_vim_500',  name:'Dishwash Liquid',     brand:'Vim',          unit:'500ml',   emoji:'🍽️', cat:'household',  basePrice:85,  tags:['bartan dhona','dishwash','vim','dish wash liquid'] },
  { id:'dishwash_pril_500', name:'Dishwash Gel',        brand:'Pril',         unit:'500ml',   emoji:'🍽️', cat:'household',  basePrice:95,  tags:['bartan dhona','dishwash','pril','dish wash gel'] },
  { id:'dishwash_vim_bar',  name:'Dishwash Bar',        brand:'Vim',          unit:'200g',    emoji:'🍽️', cat:'household',  basePrice:30,  tags:['bartan sabun','dishwash bar','vim'] },

  { id:'floor_lizol_1l',    name:'Floor Cleaner',       brand:'Lizol',        unit:'1L',       emoji:'🫧', cat:'household',  basePrice:175, tags:['floor cleaner','lizol','cleaning liquid','phenyl'] },
  { id:'toilet_harpic_750', name:'Toilet Cleaner',      brand:'Harpic',       unit:'750ml',   emoji:'🚽', cat:'household',  basePrice:155, tags:['toilet cleaner','harpic','loo cleaner'] },
  { id:'glass_colin_500',   name:'Glass Cleaner',       brand:'Colin',        unit:'500ml',   emoji:'🪟', cat:'household',  basePrice:115, tags:['glass cleaner','colin','mirror cleaner'] },

  { id:'tissue_6r',         name:'Toilet Tissue Rolls', brand:'Renova',       unit:'6 rolls', emoji:'🧻', cat:'household',  basePrice:220, tags:['tissue paper','toilet paper','toilet roll','tissue'] },
  { id:'tissue_12r',        name:'Toilet Tissue Rolls', brand:'Renova',       unit:'12 rolls',emoji:'🧻', cat:'household',  basePrice:420, tags:['tissue paper','toilet paper','toilet roll','tissue'] },
  { id:'garbage_bags_30',   name:'Garbage Bags',        brand:'Ezee',         unit:'30 pcs',  emoji:'🗑️', cat:'household',  basePrice:95,  tags:['garbage bag','dustbin bag','trash bag','ezee'] },
  { id:'aluminium_foil',    name:'Aluminium Foil',      brand:'Tata',         unit:'9m',      emoji:'✨', cat:'household',  basePrice:75,  tags:['aluminium foil','aluminum foil','tata'] },
  { id:'air_freshener_odo', name:'Air Freshener',       brand:'Odonil',       unit:'50g',     emoji:'🌸', cat:'household',  basePrice:95,  tags:['air freshener','odonil','room freshener','fragrance'] },
  { id:'mosquito_gk_45',    name:'Liquid Vaporizer Refill',brand:'Good Knight',unit:'45 nights',emoji:'🦟',cat:'household', basePrice:85,  tags:['mosquito repellent','good knight','vaporizer','mosquito'] },
  { id:'pest_mortein_425',  name:'Insect Spray',        brand:'Mortein',      unit:'425ml',   emoji:'🦟', cat:'household',  basePrice:195, tags:['insect spray','mortein','cockroach spray','pest'] },
  { id:'scrub_scotch_3',    name:'Scrub Pad',           brand:'Scotch-Brite', unit:'3 pcs',   emoji:'🧽', cat:'household',  basePrice:55,  tags:['scrub pad','scotch brite','sponge','bartan'] },
  { id:'gloves_rubber',     name:'Rubber Gloves',       brand:'3M',           unit:'1 pair',  emoji:'🧤', cat:'household',  basePrice:65,  tags:['rubber gloves','hand gloves','cleaning gloves'] },

  // ═══════════ BABY CARE ═══════════
  { id:'diaper_pam_s_20',   name:'Baby Dry Diapers S',  brand:'Pampers',      unit:'20 pcs',  emoji:'👶', cat:'baby',       basePrice:280, tags:['diaper','nappy','pampers','baby dry'] },
  { id:'diaper_pam_m_18',   name:'Baby Dry Diapers M',  brand:'Pampers',      unit:'18 pcs',  emoji:'👶', cat:'baby',       basePrice:295, tags:['diaper','nappy','pampers','baby dry'] },
  { id:'diaper_hug_m_30',   name:'Wonder Pants M',      brand:'Huggies',      unit:'30 pcs',  emoji:'👶', cat:'baby',       basePrice:495, tags:['diaper','nappy','huggies','wonder pants'] },
  { id:'baby_food_cel',     name:'Cerelac (Wheat Rice)', brand:'Nestle',       unit:'300g',    emoji:'🍼', cat:'baby',       basePrice:255, tags:['baby food','cerelac','nestle','infant food'] },
  { id:'baby_wipes_pam',    name:'Baby Wipes',          brand:'Pampers',      unit:'72 pcs',  emoji:'🧻', cat:'baby',       basePrice:245, tags:['baby wipes','wipes','pampers'] },
  { id:'baby_powder_jj',    name:'Baby Powder',         brand:"Johnson's",    unit:'200g',    emoji:'🌸', cat:'baby',       basePrice:175, tags:['baby powder','johnsons','talcum powder'] },
  { id:'baby_lotion_jj',    name:'Baby Lotion',         brand:"Johnson's",    unit:'200ml',   emoji:'🧴', cat:'baby',       basePrice:185, tags:['baby lotion','johnsons','baby moisturiser'] },

  // ═══════════ PET CARE ═══════════
  { id:'dog_food_pedigree',  name:'Adult Dog Food',     brand:'Pedigree',     unit:'1.2kg',   emoji:'🐕', cat:'petcare',    basePrice:395, tags:['dog food','pedigree','pet food','dog'] },
  { id:'cat_food_whiskas',   name:'Cat Food (Tuna)',    brand:'Whiskas',      unit:'500g',    emoji:'🐈', cat:'petcare',    basePrice:275, tags:['cat food','whiskas','pet food','cat'] },
  { id:'pet_shampoo_200',    name:'Pet Shampoo',        brand:'Himalaya',     unit:'200ml',   emoji:'🐾', cat:'petcare',    basePrice:185, tags:['pet shampoo','dog shampoo','himalaya','pet care'] },
  { id:'dog_treats_90',      name:'Dog Treats',         brand:'Pedigree',     unit:'90g',     emoji:'🦴', cat:'petcare',    basePrice:115, tags:['dog treats','pedigree','pet treats'] },
];

// ——— APP CONFIGURATIONS ———
const APPS = [
  {
    id: 'blinkit', name: 'Blinkit', emoji: '⚡', color: '#F8C200', textColor: '#000',
    eta: '8–12 min', priceMultiplier: { default: 1.00 }, freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 25 : 0,
    handlingFee:  ()    => 5,
    platformFee:  ()    => 5,
    smallOrderFee:(sub) => sub < 99  ? 15 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://blinkit.com/',
  },
  {
    id: 'zepto', name: 'Zepto', emoji: '🚀', color: '#FF3F6C', textColor: '#fff',
    eta: '10–15 min', priceMultiplier: { default: 0.98 }, freeDeliveryAbove: 149,
    deliveryFee:  (sub) => sub < 149 ? 30 : 0,
    handlingFee:  ()    => 2,
    platformFee:  ()    => 3,
    smallOrderFee:(sub) => sub < 79  ? 20 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Chennai'],
    deeplink: () => 'https://www.zeptonow.com/',
  },
  {
    id: 'swiggy_instamart', name: 'Instamart', emoji: '🟠', color: '#FC8019', textColor: '#fff',
    eta: '15–25 min', priceMultiplier: { default: 1.02 }, freeDeliveryAbove: 299,
    deliveryFee:  (sub) => sub < 299 ? 40 : 0,
    handlingFee:  ()    => 10,
    platformFee:  ()    => 5,
    smallOrderFee:()    => 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://www.swiggy.com/instamart',
  },
  {
    id: 'bigbasket_now', name: 'BB Now', emoji: '🟢', color: '#84C225', textColor: '#fff',
    eta: '10–20 min', priceMultiplier: { default: 1.01 }, freeDeliveryAbove: 249,
    deliveryFee:  (sub) => sub < 249 ? 35 : 0,
    handlingFee:  ()    => 0,
    platformFee:  ()    => 10,
    smallOrderFee:(sub) => sub < 99  ? 25 : 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Chennai','Kolkata'],
    deeplink: () => 'https://www.bigbasket.com/bbqinstant/',
  },
  {
    id: 'dunzo', name: 'Dunzo Daily', emoji: '🏪', color: '#00C5A2', textColor: '#fff',
    eta: '20–30 min', priceMultiplier: { default: 0.97 }, freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 20 : 0,
    handlingFee:  ()    => 5,
    platformFee:  ()    => 0,
    smallOrderFee:(sub) => sub < 99  ? 10 : 0,
    available: ['Mumbai','Delhi','Bangalore','Pune','Chennai','Hyderabad'],
    deeplink: () => 'https://www.dunzo.com/',
  },
  {
    id: 'jiomart', name: 'JioMart', emoji: '🔵', color: '#1A73E8', textColor: '#fff',
    eta: '2–4 hrs', priceMultiplier: { default: 0.95 }, freeDeliveryAbove: 199,
    deliveryFee:  (sub) => sub < 199 ? 29 : 0,
    handlingFee:  ()    => 0,
    platformFee:  ()    => 0,
    smallOrderFee:()    => 0,
    available: ['Mumbai','Delhi','Bangalore','Hyderabad','Pune','Kolkata','Ahmedabad','Chennai'],
    deeplink: () => 'https://www.jiomart.com/',
  },
];
